#!/usr/bin/env bash
# Bootstraps the development environment:
#   - Python venv (.venv) with the extraction/analysis libraries
#   - Ghidra + Java 21 detection, written to local.env (not versioned)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"

echo "[+] Python venv"
python3 -m venv "$ROOT/.venv"
"$ROOT/.venv/bin/pip" install -q --upgrade pip
"$ROOT/.venv/bin/pip" install -q -r "$ROOT/requirements.txt"

echo "[+] Java"
if ! java -version 2>&1 | grep -qE 'version "(2[1-9]|[3-9][0-9])'; then
	echo "    Java 21+ is required by Ghidra 12 (e.g. sudo apt install openjdk-21-jdk)" >&2
fi

echo "[+] Ghidra"
[ -f "$ROOT/local.env" ] && source "$ROOT/local.env"
if [ -z "${GHIDRA_INSTALL_DIR:-}" ] || [ ! -x "$GHIDRA_INSTALL_DIR/support/analyzeHeadless" ]; then
	GHIDRA_INSTALL_DIR=""
	for d in "$HOME"/tools/ghidra_* /opt/ghidra* "$HOME"/ghidra_*; do
		[ -x "$d/support/analyzeHeadless" ] && GHIDRA_INSTALL_DIR="$d"
	done
fi
if [ -z "$GHIDRA_INSTALL_DIR" ]; then
	echo "    Ghidra not found: download https://github.com/NationalSecurityAgency/ghidra/releases" >&2
	echo "    and extract it to ~/tools/, or set GHIDRA_INSTALL_DIR in local.env" >&2
elif LC_ALL=C grep -q '[^ -~]' <<<"$GHIDRA_INSTALL_DIR"; then
	# Ghidra's logging config fails to load from a path with non-ASCII characters.
	echo "    WARNING: $GHIDRA_INSTALL_DIR contains non-ASCII characters; move Ghidra (e.g. to ~/tools/)" >&2
fi
cat > "$ROOT/local.env" <<EOF
# Machine-specific settings (not versioned). Generated by setup.sh.
GHIDRA_INSTALL_DIR="$GHIDRA_INSTALL_DIR"
EOF
echo "    GHIDRA_INSTALL_DIR=${GHIDRA_INSTALL_DIR:-<unset>}"

echo "[+] Done. Put your decrypted CIA in cia/ and run: make"
