; Generated by tools/amxport.py from bots_joueur.pasm (v0) for v5200: edit bots_joueur.pasm or v5200.toml, then run
;   tools/amxport.py pscope_player --pasm mods/en-ligne/bots_joueur.pasm mods/en-ligne/bots_joueur-v5200.pasm --overrides mods/en-ligne/v5200.toml
; pscope_player: against the server's bots, a player's hull counts the bots as players. func_14f60 gives a
; player 100, times the other team's size over its own when outnumbered (1 against 4: 400), and counted only
; the players; the bots get the same (bots_ia.p teamSize).

; func_14f60: getTeamPlayerCount(1), getTeamPlayerCount(2) (func_3500) -> teamSize(team).
.hook 0x1a83c
    call @teamSize
    .return

.hook 0x1a868
    call @teamSize
    .return

; teamSize(team): its players, or the size the server set (server.bots.mine for the players' team, the one
; with more players; server.bots.other), whichever is more.
teamSize:
    proc
    push.s 12
    push.c 4
    call 0x3a28                     ; getTeamPlayerCount(team)
    push.pri
    push.c "server.bots"
    sysreq.n sysGetGlobal, 1
    jzer @size_players
    push.c "team.02.players"
    sysreq.n sysGetGlobal, 1
    push.pri
    push.c "team.01.players"
    sysreq.n sysGetGlobal, 1
    pop.alt                         ; alt: players of team 2, pri: of team 1
    jsless @players_two
    const.pri 1
    jump @players_team
players_two:
    const.pri 2
players_team:
    load.s.alt 12
    jeq @size_mine
    push.c "server.bots.other"
    jump @size_get
size_mine:
    push.c "server.bots.mine"
size_get:
    sysreq.n sysGetGlobal, 1
    pop.alt                         ; the players of the team
    jsgeq @size_done
    move.pri
size_done:
    retn
size_players:
    pop.pri
    retn
