; Generated by tools/pawn2pasm.py from src/bots_ia.p: edit the source, then run
;   tools/pawn2pasm.py mods/en-ligne/src/bots_ia.p
; Target: amx/surface_sub.amx.

.data_at 0x4524
.cells $pawn_data 0x0, 0xa, 0x6, 0x3, 0x0, 0x28, 0xc, 0x0, 0x0, 0x3d0f5c29, 0x3c23d70a, 0x0, 0x0, 0x3eb33333, 0x3f4ccccd, 0x3f800000
.cells $pawn_data1 0x0, 0x1, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3d0f5c29, 0x3eb851ec, 0x3ecccccd, 0x1, 0x6
.cells $pawn_data2 0x0, 0xb4, 0x0, 0x55, 0x0, 0x0, 0x42053333, 0x42c80000, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
.cells $pawn_data3 0x0, 0x0, -1013579776, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, -943501312, 0x0, 0x0, 0x0, 0x0
.cells $pawn_data4 0x0, 0x0, 0x0, -1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
.cells $pawn_data5 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
.cells $pawn_data6 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, -1000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
.cells $pawn_data7 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6e, 0x70
.cells $pawn_data8 0x63, 0x0, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x6c, 0x65
.cells $pawn_data9 0x76, 0x65, 0x6c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74, 0x65, 0x61, 0x6d
.cells $pawn_data10 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x0, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x0, 0x73
.cells $pawn_data11 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x73, 0x75, 0x62, 0x25, 0x64
.cells $pawn_data12 0x0, 0x70, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x70, 0x6c, 0x79, 0x25, 0x30, 0x32, 0x64, 0x5f
.cells $pawn_data13 0x73, 0x74, 0x61, 0x74, 0x73, 0x0, 0x6d, 0x61, 0x78, 0x54, 0x75, 0x72, 0x6e, 0x0, 0x62, 0x65
.cells $pawn_data14 0x6c, 0x6f, 0x77, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x0, 0x64, 0x69, 0x76, 0x65, 0x52, 0x61, 0x74
.cells $pawn_data15 0x65, 0x0, 0x74, 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x0, 0x74
.cells $pawn_data16 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x4d, 0x61, 0x78, 0x0, 0x74, 0x6f, 0x72, 0x70, 0x65, 0x64
.cells $pawn_data17 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x0, 0x74
.cells $pawn_data18 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x46, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76
.cells $pawn_data19 0x61, 0x6c, 0x0, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x55, 0x73, 0x65, 0x41, 0x69, 0x72, 0x0
.cells $pawn_data20 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x74, 0x75, 0x72, 0x6e, 0x0, 0x6d, 0x61
.cells $pawn_data21 0x78, 0x54, 0x75, 0x72, 0x6e, 0x5f, 0x25, 0x64, 0x0, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x62
.cells $pawn_data22 0x65, 0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x0, 0x62, 0x65, 0x6c, 0x6f, 0x77
.cells $pawn_data23 0x41, 0x63, 0x63, 0x65, 0x6c, 0x5f, 0x25, 0x64, 0x0, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64
.cells $pawn_data24 0x69, 0x76, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x0, 0x64, 0x69, 0x76, 0x65, 0x52, 0x61, 0x74
.cells $pawn_data25 0x65, 0x5f, 0x25, 0x64, 0x0, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x0, 0x74
.cells $pawn_data26 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x0, 0x6c, 0x69, 0x66, 0x65, 0x0, 0x61, 0x63
.cells $pawn_data27 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x0, 0x74, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72
.cells $pawn_data28 0x0, 0x6c, 0x69, 0x66, 0x65, 0x0, 0x0, 0x0, 0x0, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x67, 0x61
.cells $pawn_data29 0x6d, 0x65, 0x6f, 0x76, 0x65, 0x72, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x74, 0x69
.cells $pawn_data30 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x0, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x74
.cells $pawn_data31 0x65, 0x72, 0x0, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x0, 0x6e, 0x70, 0x63, 0x0, 0x61, 0x63, 0x74
.cells $pawn_data32 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x0, 0x74, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x0
.cells $pawn_data33 0x62, 0x6f, 0x74, 0x73, 0x68, 0x6f, 0x74, 0x0, 0x73, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f
.cells $pawn_data34 0x74, 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x5f, 0x6c, 0x76, 0x25, 0x30, 0x32, 0x64, 0x0, 0x62
.cells $pawn_data35 0x65, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x0, 0x73, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x74
.cells $pawn_data36 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x5f, 0x70, 0x5f, 0x68, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x0
.cells $pawn_data37 0x70, 0x5f, 0x68, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x0, 0x40, 0x6c, 0x6f, 0x63, 0x6b, 0x4f, 0x6e
.cells $pawn_data38 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x0, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x0, 0x6d, 0x61
.cells $pawn_data39 0x73, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x0, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x0, 0x6d
.cells $pawn_data40 0x61, 0x73, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x0, 0x0, 0x3ecccccd, 0x3f4ccccd, 0x3fa66666, 0x3ff33333, 0x40200000, 0x74
.cells $pawn_data41 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x0

; ---- hand-written: hooks into the game's code ----
; main: after func_e098 (the sub's properties), is it one of ours, and its look (botLook).
.hook 0xcf80
    .original
    push.c 0
    call @pw_botInit
    push.c 0
    call @botLook
    .return

; func_a848 (movement, every frame): the pilot's, while afloat.
.hook 0xa84c
    push.c 0
    call @pw_botPilot
    jzer @a848_game
    zero.pri
    retn
a848_game:
    .original
    .return

; func_edf4 (the game's bot, from func_a848): not for ours, even sinking.
.hook 0xedf8
    push.c 0
    call @pw_botLevel
    jzer @brain_game
    zero.pri
    retn
brain_game:
    .original
    .return

; ---- the bots of the battles against the server's bots: like players --------------------------------

; registerInViews (online bot): its name and level, not the game's "CPU" (name_npc).
.hook 0x2d88
    push.adr -0x180                 ; the label's text, a local of registerInViews
    push.c 4
    call @botLabel
    jnz 0x2da8                      ; done: the label is drawn as the game does
    .original
    .return

; main, online bot: registerInViews(team, camera = 0, label = 1). A bot that looks like a player is in
; the camera's list too, as players are: spectators can follow it.
.hook 0xd530
    push.c 1
    push.c 0
    call @isBot
    push.pri
    push.c 1
    .return

.hook 0xd55c
    push.c 1
    push.c 0
    call @isBot
    push.pri
    push.c 2
    .return

isBot:
    proc
    push.c 0                        ; -4
    push.c 0
    push.adr -4
    push.c "botIndex"
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    stack 4
    zero.alt
    neq
    retn

; botLook(): the hull of a player's submarine (server.bots.sub<k>: modelship, prop_anim, prop_offset of
; bxml/pscope_plyNN), with three random colours of the customisation (swatch_color), on the body.
; locals: -4 k, -8 sub, -12 other actor, -16 slot, -20 colour, -36 rgb (4 cells), -48 offset (3 cells),
; -0x1b0 text (96 cells), -0x330 model (96 cells), -0x4b0 animation (96 cells)
botLook:
    proc
    stack -0x4b0
    zero.pri
    addr.alt -0x4b0
    fill 0x4b0
    push.c 0
    push.adr -4
    push.c "botIndex"
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    jzer @look_done
    push.adr -4
    push.c "server.bots.sub%d"
    push.c 0
    push.c 96
    push.adr -0x1b0
    sysreq.n strformat, 5
    push.adr -0x1b0
    sysreq.n sysGetGlobal, 1
    stor.s.pri -8
    load.s.pri -8                   ; 1 to 23
    const.alt 1
    jsgeq @sub_low
    const.s -8, 1
sub_low:
    load.s.pri -8
    const.alt 23
    jsleq @sub_ok
    const.s -8, 23
sub_ok:
    push.adr -8
    push.c "pscope_ply%02d"
    push.c 0
    push.c 96
    push.adr -0x1b0
    sysreq.n strformat, 5
    sysreq.n worldNewActor, 0
    stor.s.pri -12
    push.s -12
    push.adr -0x1b0
    sysreq.n actorReadProperties, 2
    push.s -12
    push.adr -0x330
    push.c "modelship"
    sysreq.n actorGetPropString, 3
    push.s -12
    push.adr -0x4b0
    push.c "prop_anim"
    sysreq.n actorGetPropString, 3
    push.s -12
    push.adr -48
    push.c "prop_offset"
    sysreq.n actorGetPropVector, 3
    push.s -12
    sysreq.n actorKill, 1
    load.s.pri -0x330
    jzer @look_done                 ; no hull: the bot keeps the game's
    push.c 0
    push.c 1
    push.c 1
    push.adr -0x330
    sysreq.n actorSetModel, 4       ; its own copy, for its own colours
    push.c 0
    push.adr -0x4b0
    push.c "prop_anim"
    sysreq.n actorSetPropString, 3
    push.c 0
    push.adr -48
    push.c "prop_offset"
    sysreq.n actorSetPropVector, 3
    sysreq.n worldNewActor, 0       ; the colours of the customisation menu
    stor.s.pri -12
    push.s -12
    push.c "swatch_color"
    sysreq.n actorReadProperties, 2
    zero.s -16
colour_loop:
    push.c 33
    sysreq.n random, 1
    stor.s.pri -20
    push.adr -20
    push.c "color_%02d"
    push.c 0
    push.c 96
    push.adr -0x1b0
    sysreq.n strformat, 5
    push.s -12
    push.adr -36
    push.adr -0x1b0
    sysreq.n actorGetPropRGB, 3
    push.c 0                        ; this actor
    push.c 255
    push.s -28                      ; blue
    push.s -32                      ; green
    push.s -36                      ; red
    push.s -16
    push.c "body_mat"
    sysreq.n actorSetModelColor, 7
    inc.s -16
    load.s.pri -16
    const.alt 3
    jsless @colour_loop
    push.s -12
    sysreq.n actorKill, 1
look_done:
    stack 0x4b0
    zero.pri
    retn

; botLabel(text): "name Lv n" of a bot (botIndex k), 1; 0 for another computer sub.
; locals: -4 k, -8 level, -0x188 work, -0x308 name, -0x488 level text, -0x608 format (96 cells each)
botLabel:
    proc
    stack -0x608
    zero.pri
    addr.alt -0x608
    fill 0x608
    push.c 0
    push.adr -4
    push.c "botIndex"
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    jzer @label_none
    push.adr -4
    push.c "server.bots.name%d"
    push.c 0
    push.c 96
    push.adr -0x188
    sysreq.n strformat, 5
    push.c 0
    push.c 96
    push.adr -0x308
    push.adr -0x188
    sysreq.n sysGetGlobalArray, 4
    push.adr -4
    push.c "server.bots.lv%d"
    push.c 0
    push.c 96
    push.adr -0x188
    sysreq.n strformat, 5
    push.adr -0x188
    sysreq.n sysGetGlobal, 1
    stor.s.pri -8
    push.c 96
    push.c "lobby_player_lv"        ; "Lv %d", in the language of the game
    push.adr -0x608
    sysreq.n sysGetString, 3
    push.adr -8
    push.adr -0x608
    push.c 0
    push.c 96
    push.adr -0x488
    sysreq.n strformat, 5
    push.adr -0x488
    push.adr -0x308
    push.c "%s %s"
    push.c 0
    push.c 96
    push.s 12
    sysreq.n strformat, 6
    const.pri 1
    jump @label_done
label_none:
    zero.pri
label_done:
    stack 0x608
    retn

; ---- compiled ----
pw_operatorsub_Float:
    proc
    load.s.pri 0xc
    const.alt -2147483648
    xor
    retn
pw_operatoreqeq_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    zero.alt
    eq
    retn
pw_operatornoteq_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    zero.alt
    neq
    retn
pw_operatorgt_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    move.alt
    zero.pri
    xchg
    sgrtr
    retn
pw_operatorgteq_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    move.alt
    zero.pri
    xchg
    sgeq
    retn
pw_operatorlt_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    move.alt
    zero.pri
    xchg
    sless
    retn
pw_operatorlteq_Float_Float:
    proc
    push.s 0x10
    push.s 0xc
    sysreq.n floatcmp, 2
    move.alt
    zero.pri
    xchg
    sleq
    retn
pw_fabs:
    proc
    load.s.pri 0xc
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l0
    push.s 0xc
    push.c 0x4
    call @pw_operatorsub_Float
    jump @bots_ia_l1
bots_ia_l0:
    load.s.pri 0xc
bots_ia_l1:
    retn
pw_fmin:
    proc
    load.s.pri 0x10
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l2
    load.s.pri 0xc
    jump @bots_ia_l3
bots_ia_l2:
    load.s.pri 0x10
bots_ia_l3:
    retn
pw_fmax:
    proc
    load.s.pri 0x10
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l4
    load.s.pri 0xc
    jump @bots_ia_l5
bots_ia_l4:
    load.s.pri 0x10
bots_ia_l5:
    retn
pw_fclamp:
    proc
    load.s.pri 0x10
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l6
    load.s.pri 0x10
    jump @bots_ia_l7
bots_ia_l6:
    load.s.pri 0x14
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l8
    load.s.pri 0x14
    jump @bots_ia_l9
bots_ia_l8:
    load.s.pri 0xc
bots_ia_l9:
bots_ia_l7:
    retn
pw_wrapAngle:
    proc
bots_ia_l10:
    const.pri 0x40490fda
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l11
    load.s.pri 0xc
    push.pri
    push.c 0x40490fda
    push.c 0x40000000
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    stor.s.pri 0xc
    jump @bots_ia_l10
bots_ia_l11:
bots_ia_l12:
    const.pri -1068953638
    load.s.alt 0xc
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l13
    load.s.pri 0xc
    push.pri
    push.c 0x40490fda
    push.c 0x40000000
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri 0xc
    jump @bots_ia_l12
bots_ia_l13:
    load.s.pri 0xc
    retn
pw_yawOf:
    proc
    load.s.pri 0xc
    add.c 0x8
    load.i
    push.pri
    load.s.pri 0xc
    load.i
    push.pri
    sysreq.n floatatan2, 2
    retn
pw_headingOf:
    proc
    push.c 0x0
    push.s 0x10
    sysreq.n floatcos, 2
    push.pri
    push.c 0x0
    push.c 0x0
    push.s 0x10
    sysreq.n floatsin, 2
    push.pri
    push.s 0xc
    sysreq.n floatvecset, 4
    zero.pri
    retn
pw_distance:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.s 0x10
    push.s 0xc
    push.adr -12
    sysreq.n floatvecsubto, 3
    push.adr -12
    sysreq.n floatveclength, 1
    stack 0xc
    retn
pw_distance2D:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.s 0x10
    push.s 0xc
    push.adr -12
    sysreq.n floatvecsubto, 3
    addr.pri -12
    add.c 0x4
    move.alt
    zero.pri
    stor.i
    push.adr -12
    sysreq.n floatveclength, 1
    stack 0xc
    retn
pw_frandom:
    proc
    sysreq.n floatrnd, 0
    retn
pw_botInit:
    proc
    push.c 0x0
    zero 0x4574
    load.pri 0x1f28
    jnz @bots_ia_l14
    zero.pri
    stack 0x4
    retn
bots_ia_l14:
    push.c 0x0
    push.adr -4
    push.c 0x471c
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    jnz @bots_ia_l15
    zero.pri
    stack 0x4
    retn
bots_ia_l15:
    push.c 0x472c
    sysreq.n sysGetGlobal, 1
    stor.pri 0x4574
    load.pri 0x4574
    const.alt 0x1
    jsgeq @bots_ia_l16
    const.pri 0x2
    stor.pri 0x4574
bots_ia_l16:
    load.pri 0x4574
    const.alt 0x3
    jsleq @bots_ia_l17
    const.pri 0x3
    stor.pri 0x4574
bots_ia_l17:
    load.pri 0x4574
    stack 0x4
    retn
pw_botLevel:
    proc
    load.pri 0x4574
    retn
pw_botPilot:
    proc
    load.pri 0x4574
    jzer @bots_ia_l19
    load.pri 0x1c90
    jzer @bots_ia_l19
    const.pri 0x3c23d70a
    load.alt 0x1c68
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jnz @bots_ia_l19
    zero.pri
    jump @bots_ia_l20
bots_ia_l19:
    const.pri 0x1
bots_ia_l20:
    jzer @bots_ia_l18
    load.pri 0x4578
    jzer @bots_ia_l22
    load.pri 0x45c4
    jzer @bots_ia_l22
    const.pri 0x1
    jump @bots_ia_l23
bots_ia_l22:
    zero.pri
bots_ia_l23:
    jzer @bots_ia_l21
    push.c 0x0
    call @pw_maskerOff
bots_ia_l21:
    zero.pri
    retn
bots_ia_l18:
    load.pri 0x4578
    jnz @bots_ia_l24
    push.c 0x0
    call @pw_start
bots_ia_l24:
    inc 0x457c
    push.c 0x0
    call @pw_timers
    load.pri 0x457c
    push.pri
    load.pri 0x4574
    const.alt 0x4524
    idxaddr.b 0x2
    load.i
    pop.alt
    sdiv.alt
    push.alt
    load.pri 0x4580
    push.pri
    load.pri 0x4574
    const.alt 0x4524
    idxaddr.b 0x2
    load.i
    pop.alt
    sdiv.alt
    move.pri
    pop.alt
    jneq @bots_ia_l25
    push.c 0x0
    call @pw_lookAround
bots_ia_l25:
    push.c 0x0
    call @pw_follow
    push.c 0x0
    call @pw_decide
    const.pri 0x3
    load.alt 0x457c
    sdiv.alt
    move.pri
    jnz @bots_ia_l26
    push.c 0x0
    call @pw_steerClear
bots_ia_l26:
    push.c 0x0
    call @pw_move
    const.pri 0x1
    retn
pw_botDebug:
    proc
    load.s.pri 0xc
    push.pri
    push 0x4630
    sysreq.n float, 1
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x4
    push.pri
    const.pri 0x4638
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x8
    push.pri
    const.pri 0x4638
    add.c 0x4
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0xc
    push.pri
    const.pri 0x4638
    add.c 0x8
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x10
    push.pri
    const.pri 0x4644
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x14
    push.pri
    const.pri 0x4644
    add.c 0x4
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x18
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x1c
    move.alt
    load.pri 0x4650
    stor.i
    load.s.pri 0xc
    add.c 0x20
    move.alt
    load.pri 0x45e4
    stor.i
    load.s.pri 0xc
    add.c 0x24
    move.alt
    load.pri 0x45e0
    stor.i
    load.s.pri 0xc
    add.c 0x28
    move.alt
    load.pri 0x45ec
    stor.i
    load.s.pri 0xc
    add.c 0x2c
    push.pri
    push 0x45a4
    sysreq.n float, 1
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x30
    move.alt
    load.pri 0x4774
    stor.i
    load.s.pri 0xc
    add.c 0x34
    move.alt
    load.pri 0x45e8
    stor.i
    load.s.pri 0xc
    add.c 0x38
    push.pri
    push 0x46c8
    sysreq.n float, 1
    pop.alt
    stor.i
    load.s.pri 0xc
    add.c 0x3c
    move.alt
    load.pri 0x4610
    stor.i
    const.pri 0x1
    retn
.public @eventCollide
pw_at_eventCollide:
    proc
    load.pri 0x4574
    jzer @bots_ia_l28
    load.pri 0x4578
    jzer @bots_ia_l28
    zero.pri
    jump @bots_ia_l29
bots_ia_l28:
    const.pri 0x1
bots_ia_l29:
    jzer @bots_ia_l27
    zero.pri
    retn
bots_ia_l27:
    stack -4
    push.s 0xc
    sysreq.n actorGetCollisionType, 1
    stor.s.pri -4
    load.s.pri -4
    const.alt 0xc0001
    and
    jnz @bots_ia_l30
    zero.pri
    stack 0x4
    retn
bots_ia_l30:
    load.s.pri -4
    const.alt 0x1
    and
    jzer @bots_ia_l31
    const.pri 0x40c00000
    jump @bots_ia_l32
bots_ia_l31:
    const.pri 0x40800000
bots_ia_l32:
    push.pri
    push.s 0x14
    push.c 0x45f4
    sysreq.n floatvecaddscale, 3
    load.s.pri 0x14
    const.alt 0x4600
    movs 0xc
    const.pri 0xc
    stor.pri 0x460c
    zero.pri
    stack 0x4
    retn
pw_start:
    proc
    const.pri 0x1
    stor.pri 0x4578
    sysreq.n actorGetID, 0
    stor.pri 0x4580
    push.c 0x0
    push.c 0x4584
    push.c 0x4794
    sysreq.n actorGetPropInt, 3
    const.pri 0x3f800000
    load.alt 0x1c68
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l33
    load.pri 0x1c68
    jump @bots_ia_l34
bots_ia_l33:
    const.pri 0x43160000
bots_ia_l34:
    stor.pri 0x4588
    load.pri 0x1c68
    stor.pri 0x458c
    push.c 0x0
    call @pw_readSubmarine
    load.pri 0x45a0
    stor.pri 0x45a4
    load.pri 0x4574
    const.alt 0x4564
    idxaddr.b 0x2
    load.i
    stor.pri 0x45b8
    load.pri 0x1cc8
    stor.pri 0x45e4
    load.pri 0x1cc8
    stor.pri 0x45e8
    push.c -1013579776
    const.pri 0x1ca0
    add.c 0x4
    load.i
    push.pri
    push.c 0x8
    call @pw_fmin
    stor.pri 0x45ec
    const.pri 0x4614
    move.alt
    const.pri 0x1ca0
    movs 0xc
    push.c 0x0
    push.c 0xc0011
    sysreq.n actorSetCollisionCheck, 2
    push.c 0x45cc
    sysreq.n floatveczero, 1
    push.c 0x45f4
    sysreq.n floatveczero, 1
    zero.pri
    retn
pw_readSubmarine:
    proc
    push.c 0x0
    push.c 0x1
    stack -192
    zero.pri
    addr.alt -200
    fill 0xc0
    push.c 0x0
    push.adr -4
    push.c 0x47bc
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    jzer @bots_ia_l35
    push.adr -4
    push.c 0x47e0
    push.c 0x0
    push.c 0x30
    push.adr -200
    sysreq.n strformat, 5
    push.adr -200
    sysreq.n sysGetGlobal, 1
    stor.s.pri -8
    load.s.pri -8
    const.alt 0x1
    jsless @bots_ia_l37
    load.s.pri -8
    const.alt 0x17
    jsgrtr @bots_ia_l37
    zero.pri
    jump @bots_ia_l38
bots_ia_l37:
    const.pri 0x1
bots_ia_l38:
    jzer @bots_ia_l36
    const.pri 0x1
    stor.s.pri -8
bots_ia_l36:
bots_ia_l35:
    stack -4
    sysreq.n worldNewActor, 0
    stor.s.pri -204
    push.adr -8
    push.c 0x4828
    push.c 0x0
    push.c 0x30
    push.adr -200
    sysreq.n strformat, 5
    push.s -204
    push.adr -200
    sysreq.n actorReadProperties, 2
    push.c 0x4
    push.c 0x4
    push.c 0x4
    push.c 0x6
    push.s -204
    push.adr -208
    push.c 0x487c
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.adr -212
    push.c 0x489c
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.adr -216
    push.c 0x48c8
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.c 0x459c
    push.c 0x48ec
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.c 0x45a0
    push.c 0x4920
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.adr -220
    push.c 0x494c
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.c 0x45b0
    push.c 0x49a0
    sysreq.n actorGetPropInt, 3
    push.s -204
    push.c 0x45bc
    push.c 0x49f0
    sysreq.n actorGetPropReal, 3
    push.s -204
    push.c 0x4a24
    sysreq.n actorReadProperties, 2
    push.adr -208
    push.c 0x4a5c
    push.c 0x0
    push.c 0x30
    push.adr -200
    sysreq.n strformat, 5
    push.s -204
    push.c 0x4590
    push.adr -200
    sysreq.n actorGetPropReal, 3
    push.s -204
    push.c 0x4a88
    sysreq.n actorReadProperties, 2
    push.adr -212
    push.c 0x4ad0
    push.c 0x0
    push.c 0x30
    push.adr -200
    sysreq.n strformat, 5
    push.s -204
    push.c 0x4594
    push.adr -200
    sysreq.n actorGetPropReal, 3
    push.s -204
    push.c 0x4b08
    sysreq.n actorReadProperties, 2
    push.adr -216
    push.c 0x4b48
    push.c 0x0
    push.c 0x30
    push.adr -200
    sysreq.n strformat, 5
    push.s -204
    push.c 0x4598
    push.adr -200
    sysreq.n actorGetPropReal, 3
    push.s -204
    sysreq.n actorKill, 1
    load.pri 0x459c
    const.alt 0x1
    jsless @bots_ia_l40
    load.pri 0x459c
    const.alt 0x3
    jsgrtr @bots_ia_l40
    zero.pri
    jump @bots_ia_l41
bots_ia_l40:
    const.pri 0x1
bots_ia_l41:
    jzer @bots_ia_l39
    const.pri 0x1
    stor.pri 0x459c
bots_ia_l39:
    load.pri 0x45a0
    const.alt 0x1
    jsgeq @bots_ia_l42
    const.pri 0x6
    stor.pri 0x45a0
bots_ia_l42:
    load.s.pri -220
    move.alt
    zero.pri
    xchg
    jsleq @bots_ia_l43
    load.s.pri -220
    jump @bots_ia_l44
bots_ia_l43:
    const.pri 0x6
bots_ia_l44:
    smul.c 0x1e
    stor.pri 0x45a8
    load.pri 0x45b0
    const.alt 0x1e
    jsgeq @bots_ia_l45
    const.pri 0x55
    stor.pri 0x45b0
bots_ia_l45:
    load.pri 0x45bc
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jzer @bots_ia_l46
    const.pri 0x42053333
    stor.pri 0x45bc
bots_ia_l46:
    push.c 0x3db851ec
    push.c 0x3c23d70a
    push 0x4590
    push.c 0xc
    call @pw_fclamp
    stor.pri 0x4590
    push.c 0x3f0a3d71
    push.c 0x3e99999a
    push 0x4594
    push.c 0xc
    call @pw_fclamp
    stor.pri 0x4594
    push.c 0x3f333333
    push.c 0x3e800000
    push 0x4598
    push.c 0xc
    call @pw_fclamp
    stor.pri 0x4598
    push.c 0x3d1ba5e3
    push 0x4594
    sysreq.n floatdiv, 2
    stor.pri 0x1c78
    stack 0xdc
    zero.pri
    retn
pw_timers:
    proc
    load.pri 0x45b4
    jzer @bots_ia_l47
    dec 0x45b4
bots_ia_l47:
    load.pri 0x45a4
    load.alt 0x45a0
    jsgeq @bots_ia_l49
    dec 0x45ac
    load.pri 0x45ac
    move.alt
    zero.pri
    xchg
    jsgrtr @bots_ia_l49
    const.pri 0x1
    jump @bots_ia_l50
bots_ia_l49:
    zero.pri
bots_ia_l50:
    jzer @bots_ia_l48
    inc 0x45a4
    load.pri 0x45a8
    stor.pri 0x45ac
bots_ia_l48:
    load.pri 0x460c
    jzer @bots_ia_l51
    dec 0x460c
bots_ia_l51:
    load.pri 0x4710
    jzer @bots_ia_l52
    dec 0x4710
bots_ia_l52:
    load.pri 0x4714
    jzer @bots_ia_l53
    dec 0x4714
bots_ia_l53:
    load.pri 0x4624
    jzer @bots_ia_l54
    dec 0x4624
bots_ia_l54:
    load.pri 0x45c4
    jzer @bots_ia_l56
    dec 0x45c4
    load.pri 0x45c4
    jnz @bots_ia_l56
    const.pri 0x1
    jump @bots_ia_l57
bots_ia_l56:
    zero.pri
bots_ia_l57:
    jzer @bots_ia_l55
    push.c 0x0
    call @pw_maskerOff
bots_ia_l55:
    load.pri 0x45c4
    jnz @bots_ia_l59
    const.pri 0x42c80000
    load.alt 0x45c0
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l59
    const.pri 0x1
    jump @bots_ia_l60
bots_ia_l59:
    zero.pri
bots_ia_l60:
    jzer @bots_ia_l58
    push 0x45c0
    push.c 0x3d4ccccd
    sysreq.n floatadd, 2
    stor.pri 0x45c0
bots_ia_l58:
    load.pri 0x1c68
    push.pri
    push.c 0x3f000000
    push 0x458c
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l61
    const.pri 0x78
    stor.pri 0x4710
bots_ia_l61:
    load.pri 0x1c68
    stor.pri 0x458c
    zero.pri
    retn
pw_clearLine:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.s 0xc
    push.s 0x10
    push.adr -12
    sysreq.n floatvecsubto, 3
    stack -4
    push.adr -12
    sysreq.n floatveclength, 1
    stor.s.pri -16
    const.pri 0x3f800000
    load.s.alt -16
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l62
    const.pri 0x1
    stack 0x10
    retn
bots_ia_l62:
    load.s.pri -16
    const.alt 0x3f800000
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    push.pri
    push.adr -12
    sysreq.n floatvecscale, 2
    push.c 0x1
    push.s -16
    push.adr -12
    push.s 0xc
    sysreq.n worldClipLine, 4
    push.pri
    load.s.pri 0x14
    load.s.alt -16
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgteq_Float_Float
    pop.alt
    stack 0x10
    retn
pw_isMasked:
    proc
    push.c 0x0
    push.s 0xc
    push.adr -4
    push.c 0x4b78
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    stack 0x4
    retn
pw_lookAround:
    proc
    stack -64
    zero.pri
    addr.alt -64
    fill 0x40
    stack -4
    push.c 0x10
    push.c 0xc0000
    push.c 0x471c4000
    push.c 0x1ca0
    push.adr -64
    sysreq.n worldFindActors, 5
    stor.s.pri -68
    push.c -1
    push.c 0x49742400
    push.c -1
    push.c 0x49742400
    zero 0x470c
    push.c 0x0
    jump @bots_ia_l65
bots_ia_l63:
    inc.s -88
bots_ia_l65:
    load.s.pri -88
    load.s.alt -68
    jsgeq @bots_ia_l64
    stack -4
    addr.alt -64
    load.s.pri -88
    lidx.b 0x2
    stor.s.pri -92
    load.pri 0x4580
    load.s.alt -92
    jneq @bots_ia_l66
    stack 0x4
    jump @bots_ia_l63
bots_ia_l66:
    push.c 0x0
    push.s -92
    push.adr -96
    push.c 0x4ba0
    sysreq.n actorGetPropInt, 3
    load.s.pri -96
    jnz @bots_ia_l67
    stack 0x8
    jump @bots_ia_l63
bots_ia_l67:
    push.c 0x3f800000
    push.s -92
    push.adr -100
    push.c 0x4bc8
    sysreq.n actorGetPropReal, 3
    const.pri 0x3c23d70a
    load.s.alt -100
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jzer @bots_ia_l68
    stack 0xc
    jump @bots_ia_l63
bots_ia_l68:
    load.pri 0x4584
    load.s.alt -96
    jneq @bots_ia_l69
    load.pri 0x470c
    const.alt 0x8
    jsgeq @bots_ia_l70
    const.pri 0x46ec
    push.pri
    load.pri 0x470c
    inc 0x470c
    pop.alt
    idxaddr.b 0x2
    move.alt
    load.s.pri -92
    stor.i
bots_ia_l70:
    stack 0xc
    jump @bots_ia_l63
bots_ia_l69:
    stack -12
    zero.pri
    addr.alt -112
    fill 0xc
    push.s -92
    push.adr -112
    sysreq.n actorGetPosition, 2
    stack -4
    push.c 0x1ca0
    push.adr -112
    push.c 0x8
    call @pw_distance
    stor.s.pri -116
    stack -4
    push.s -92
    push.c 0x4
    call @pw_isMasked
    stor.s.pri -120
    load.s.pri -120
    jnz @bots_ia_l72
    load.s.pri -84
    load.s.alt -116
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l72
    const.pri 0x1
    jump @bots_ia_l73
bots_ia_l72:
    zero.pri
bots_ia_l73:
    jzer @bots_ia_l71
    load.s.pri -92
    stor.s.pri -80
    load.s.pri -116
    stor.s.pri -84
bots_ia_l71:
    const.pri 0x460ca000
    load.s.alt -116
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l75
    load.s.pri -120
    jzer @bots_ia_l76
    const.pri 0x44960000
    load.s.alt -116
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l76
    const.pri 0x1
    jump @bots_ia_l77
bots_ia_l76:
    zero.pri
bots_ia_l77:
    jnz @bots_ia_l75
    zero.pri
    jump @bots_ia_l78
bots_ia_l75:
    const.pri 0x1
bots_ia_l78:
    jzer @bots_ia_l74
    stack 0x20
    jump @bots_ia_l63
bots_ia_l74:
    stack -4
    push.c 0x43480000
    push.adr -112
    push.c 0x1ca0
    push.c 0xc
    call @pw_clearLine
    stor.s.pri -124
    load.s.pri -124
    jnz @bots_ia_l80
    const.pri 0x453b8000
    load.s.alt -116
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l80
    const.pri 0x1
    jump @bots_ia_l81
bots_ia_l80:
    zero.pri
bots_ia_l81:
    jzer @bots_ia_l79
    stack 0x24
    jump @bots_ia_l63
bots_ia_l79:
    stack -4
    load.s.pri -116
    push.pri
    load.s.pri -100
    const.alt 0x41400000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    load.s.pri -124
    jzer @bots_ia_l82
    zero.pri
    jump @bots_ia_l83
bots_ia_l82:
    const.pri 0x451c4000
bots_ia_l83:
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -128
    load.pri 0x4630
    load.s.alt -92
    jneq @bots_ia_l84
    load.s.pri -128
    const.alt 0x3f333333
    push.pri
    push.alt
    sysreq.n floatmul, 2
    move.alt
    const.pri 0x43c80000
    push.pri
    push.alt
    sysreq.n floatsub, 2
    stor.s.pri -128
bots_ia_l84:
    load.s.pri -76
    load.s.alt -128
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l85
    load.s.pri -128
    stor.s.pri -76
    load.s.pri -92
    stor.s.pri -72
bots_ia_l85:
    stack 0x28
    jump @bots_ia_l63
bots_ia_l64:
    stack 0x4
    load.pri 0x4630
    load.s.alt -72
    jeq @bots_ia_l86
    load.s.pri -72
    stor.pri 0x4630
    load.pri 0x457c
    stor.pri 0x4634
    zero 0x46b4
    push.c 0x4644
    sysreq.n floatveczero, 1
    zero 0x4650
    zero 0x46c0
    const.pri -1000
    stor.pri 0x46c4
bots_ia_l86:
    load.pri 0x4630
    eq.c.pri -1
    jzer @bots_ia_l88
    load.s.pri -80
    const.alt -1
    jeq @bots_ia_l88
    load.pri 0x46e8
    jzer @bots_ia_l89
    const.pri 0x5a
    load.alt 0x457c
    sdiv.alt
    push.alt
    load.pri 0x4574
    const.alt 0x4524
    idxaddr.b 0x2
    load.i
    pop.alt
    xchg
    jsless @bots_ia_l89
    zero.pri
    jump @bots_ia_l90
bots_ia_l89:
    const.pri 0x1
bots_ia_l90:
    jzer @bots_ia_l88
    const.pri 0x1
    jump @bots_ia_l91
bots_ia_l88:
    zero.pri
bots_ia_l91:
    jzer @bots_ia_l87
    push.s -80
    push.c 0x46dc
    sysreq.n actorGetPosition, 2
    const.pri 0x1
    stor.pri 0x46e8
bots_ia_l87:
    push.c 0x0
    call @pw_watchTorpedoes
    stack 0x54
    zero.pri
    retn
pw_watchTorpedoes:
    proc
    load.pri 0x4714
    jzer @bots_ia_l92
    zero.pri
    retn
bots_ia_l92:
    stack -32
    zero.pri
    addr.alt -32
    fill 0x20
    stack -4
    push.c 0x8
    push.c 0x18
    push.c 0x455ac000
    push.c 0x1ca0
    push.adr -32
    sysreq.n worldFindActors, 5
    stor.s.pri -36
    push.c 0x0
    jump @bots_ia_l95
bots_ia_l93:
    inc.s -40
bots_ia_l95:
    load.s.pri -40
    load.s.alt -36
    jsgeq @bots_ia_l94
    stack -4
    addr.alt -32
    load.s.pri -40
    lidx.b 0x2
    stor.s.pri -44
    push.c 0x0
    push.s -44
    push.adr -48
    push.c 0x4bdc
    sysreq.n actorGetPropInt, 3
    load.pri 0x4580
    load.s.alt -48
    jneq @bots_ia_l96
    stack 0x8
    jump @bots_ia_l93
bots_ia_l96:
    push.c 0x0
    push.s -44
    push.adr -52
    push.c 0x4c00
    sysreq.n actorGetPropInt, 3
    load.s.pri -52
    jzer @bots_ia_l98
    load.pri 0x4584
    load.s.alt -52
    jneq @bots_ia_l98
    const.pri 0x1
    jump @bots_ia_l99
bots_ia_l98:
    zero.pri
bots_ia_l99:
    jzer @bots_ia_l97
    stack 0xc
    jump @bots_ia_l93
bots_ia_l97:
    stack -12
    zero.pri
    addr.alt -64
    fill 0xc
    stack -12
    zero.pri
    addr.alt -76
    fill 0xc
    push.s -44
    push.adr -64
    sysreq.n actorGetPosition, 2
    push.s -44
    push.adr -76
    sysreq.n actorGetVelocity, 2
    stack -4
    push.adr -76
    push.adr -76
    sysreq.n floatvecdot, 2
    stor.s.pri -80
    const.pri 0x41c80000
    load.s.alt -80
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l100
    stack 0x28
    jump @bots_ia_l93
bots_ia_l100:
    stack -12
    zero.pri
    addr.alt -92
    fill 0xc
    push.adr -64
    push.c 0x1ca0
    push.adr -92
    sysreq.n floatvecsubto, 3
    stack -4
    push.adr -76
    push.adr -92
    sysreq.n floatvecdot, 2
    move.alt
    load.s.pri -80
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    stor.s.pri -96
    load.s.pri -96
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jnz @bots_ia_l102
    const.pri 0x42960000
    load.s.alt -96
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l102
    zero.pri
    jump @bots_ia_l103
bots_ia_l102:
    const.pri 0x1
bots_ia_l103:
    jzer @bots_ia_l101
    stack 0x38
    jump @bots_ia_l93
bots_ia_l101:
    push.s -96
    push.c 0x4
    call @pw_operatorsub_Float
    push.pri
    push.adr -76
    push.adr -92
    sysreq.n floatvecaddscale, 3
    push.adr -92
    sysreq.n floatveclength, 1
    move.alt
    const.pri 0x43820000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l104
    stack 0x38
    jump @bots_ia_l93
bots_ia_l104:
    push.c 0x0
    call @pw_frandom
    push.pri
    load.pri 0x4574
    const.alt 0x4554
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l105
    stack 0x38
    jump @bots_ia_l93
bots_ia_l105:
    const.pri 0x2d
    stor.pri 0x4714
    push.adr -92
    sysreq.n floatveclength, 1
    move.alt
    const.pri 0x42200000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l106
    push.adr -92
    push.c 0x4
    call @pw_yawOf
    stor.pri 0x4718
    jump @bots_ia_l107
bots_ia_l106:
    push.adr -76
    push.c 0x4
    call @pw_yawOf
    push.pri
    push.c 0x0
    call @pw_frandom
    move.alt
    const.pri 0x3f000000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l108
    const.pri 0x3fc90ff9
    jump @bots_ia_l109
bots_ia_l108:
    const.pri -1077342215
bots_ia_l109:
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x4718
bots_ia_l107:
    const.pri 0x1ca0
    add.c 0x4
    load.i
    push.pri
    const.pri 0x1ca0
    add.c 0x4
    load.i
    push.pri
    addr.pri -64
    add.c 0x4
    load.i
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l110
    const.pri 0x437a0000
    jump @bots_ia_l111
bots_ia_l110:
    const.pri -1015414784
bots_ia_l111:
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x45ec
    zero.pri
    stack 0x60
    retn
    jump @bots_ia_l93
bots_ia_l94:
    stack 0x4
    stack 0x24
    zero.pri
    retn
pw_follow:
    proc
    load.pri 0x4630
    eq.c.pri -1
    jzer @bots_ia_l112
    zero.pri
    retn
bots_ia_l112:
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x3f800000
    push 0x4630
    sysreq.n actorGetCollisionType, 1
    const.alt 0xc0000
    and
    jzer @bots_ia_l114
    push 0x4630
    push.adr -12
    sysreq.n actorGetPosition, 2
    jzer @bots_ia_l114
    push 0x4630
    push.adr -16
    push.c 0x4c28
    sysreq.n actorGetPropReal, 3
    jzer @bots_ia_l115
    const.pri 0x3c23d70a
    load.s.alt -16
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jzer @bots_ia_l115
    const.pri 0x1
    jump @bots_ia_l116
bots_ia_l115:
    zero.pri
bots_ia_l116:
    jnz @bots_ia_l114
    zero.pri
    jump @bots_ia_l117
bots_ia_l114:
    const.pri 0x1
bots_ia_l117:
    jzer @bots_ia_l113
    const.pri -1
    stor.pri 0x4630
    zero.pri
    stack 0x10
    retn
bots_ia_l113:
    push 0x4630
    push.c 0x4
    call @pw_isMasked
    jzer @bots_ia_l119
    push.c 0x1ca0
    push.adr -12
    push.c 0x8
    call @pw_distance
    move.alt
    const.pri 0x44960000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l119
    const.pri 0x1
    jump @bots_ia_l120
bots_ia_l119:
    zero.pri
bots_ia_l120:
    jzer @bots_ia_l118
    const.pri -1
    stor.pri 0x4630
    zero.pri
    stack 0x10
    retn
bots_ia_l118:
    const.pri 0x4638
    push.pri
    addr.pri -12
    pop.alt
    movs 0xc
    load.pri 0x46b8
    add.c 0x1
    move.alt
    const.pri 0x8
    sdiv.alt
    move.pri
    stor.pri 0x46b8
    const.pri 0x4654
    push.pri
    load.pri 0x46b8
    smul.c 0x3
    pop.alt
    idxaddr.b 0x2
    push.pri
    addr.pri -12
    load.i
    pop.alt
    stor.i
    const.pri 0x4654
    push.pri
    load.pri 0x46b8
    smul.c 0x3
    add.c 0x1
    pop.alt
    idxaddr.b 0x2
    push.pri
    addr.pri -12
    add.c 0x4
    load.i
    pop.alt
    stor.i
    const.pri 0x4654
    push.pri
    load.pri 0x46b8
    smul.c 0x3
    add.c 0x2
    pop.alt
    idxaddr.b 0x2
    push.pri
    addr.pri -12
    add.c 0x8
    load.i
    pop.alt
    stor.i
    load.pri 0x46b4
    const.alt 0x8
    jsgeq @bots_ia_l121
    inc 0x46b4
bots_ia_l121:
    load.pri 0x46b4
    const.alt 0x2
    jsless @bots_ia_l122
    stack -4
    load.pri 0x46b8
    add.c 0x9
    load.alt 0x46b4
    sub
    move.alt
    const.pri 0x8
    sdiv.alt
    move.pri
    stor.s.pri -20
    stack -4
    load.pri 0x46b4
    add.c -1
    push.pri
    sysreq.n float, 1
    stor.s.pri -24
    stack -12
    zero.pri
    addr.alt -36
    fill 0xc
    addr.pri -36
    push.pri
    addr.pri -12
    load.i
    push.pri
    const.pri 0x4654
    push.pri
    load.s.pri -20
    smul.c 0x3
    pop.alt
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    move.alt
    load.s.pri -24
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    pop.alt
    stor.i
    addr.pri -36
    add.c 0x4
    push.pri
    addr.pri -12
    add.c 0x4
    load.i
    push.pri
    const.pri 0x4654
    push.pri
    load.s.pri -20
    smul.c 0x3
    add.c 0x1
    pop.alt
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    move.alt
    load.s.pri -24
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    pop.alt
    stor.i
    addr.pri -36
    add.c 0x8
    push.pri
    addr.pri -12
    add.c 0x8
    load.i
    push.pri
    const.pri 0x4654
    push.pri
    load.s.pri -20
    smul.c 0x3
    add.c 0x2
    pop.alt
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    move.alt
    load.s.pri -24
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    pop.alt
    stor.i
    stack -4
    push.adr -36
    push.c 0x4
    call @pw_yawOf
    stor.s.pri -40
    stack -4
    addr.pri -36
    load.i
    push.pri
    addr.pri -36
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    addr.pri -36
    add.c 0x8
    load.i
    push.pri
    addr.pri -36
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    stor.s.pri -44
    const.pri 0x40000000
    load.s.alt -44
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l124
    load.pri 0x46b4
    const.alt 0x8
    jsless @bots_ia_l124
    const.pri 0x1
    jump @bots_ia_l125
bots_ia_l124:
    zero.pri
bots_ia_l125:
    jzer @bots_ia_l123
    push 0x4650
    push.c 0x3f4ccccd
    sysreq.n floatmul, 2
    push.pri
    push.c 0x3da3d70a
    push.c -1113336054
    load.pri 0x46bc
    load.s.alt -40
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    push.pri
    push.c 0xc
    call @pw_fclamp
    const.alt 0x3e4ccccd
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x4650
    stack -4
    const.pri 0x3ba3d70a
    load.alt 0x4650
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l126
    const.pri 0x1
    jump @bots_ia_l127
bots_ia_l126:
    const.pri -1146890486
    load.alt 0x4650
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l128
    const.pri -1
    jump @bots_ia_l129
bots_ia_l128:
    zero.pri
bots_ia_l129:
bots_ia_l127:
    stor.s.pri -48
    load.s.pri -48
    jzer @bots_ia_l131
    load.pri 0x46c0
    load.s.alt -48
    jeq @bots_ia_l131
    const.pri 0x1
    jump @bots_ia_l132
bots_ia_l131:
    zero.pri
bots_ia_l132:
    jzer @bots_ia_l130
    load.pri 0x46c0
    jzer @bots_ia_l133
    load.pri 0x457c
    stor.pri 0x46c4
bots_ia_l133:
    load.s.pri -48
    stor.pri 0x46c0
bots_ia_l130:
    stack 0x4
    jump @bots_ia_l134
bots_ia_l123:
    push 0x4650
    push.c 0x3f666666
    sysreq.n floatmul, 2
    stor.pri 0x4650
bots_ia_l134:
    load.s.pri -40
    stor.pri 0x46bc
    const.pri 0x4644
    push.pri
    addr.pri -36
    pop.alt
    movs 0xc
    stack 0x1c
bots_ia_l122:
    const.pri 0xf
    load.alt 0x457c
    sdiv.alt
    move.pri
    jzer @bots_ia_l136
    load.pri 0x4634
    load.alt 0x457c
    sub.alt
    const.alt 0x2
    jsless @bots_ia_l136
    zero.pri
    jump @bots_ia_l137
bots_ia_l136:
    const.pri 0x1
bots_ia_l137:
    jzer @bots_ia_l135
    push.c 0x43480000
    push.adr -12
    push.c 0x1ca0
    push.c 0xc
    call @pw_clearLine
    stor.pri 0x46c8
bots_ia_l135:
    const.pri 0x46cc
    push.pri
    addr.pri -12
    pop.alt
    movs 0xc
    load.pri 0x457c
    stor.pri 0x46d8
    stack 0x10
    zero.pri
    retn
pw_decide:
    proc
    stack -4
    push 0x4588
    push 0x1c68
    sysreq.n floatdiv, 2
    stor.s.pri -4
    const.pri 0x3f4ccccd
    stor.pri 0x45e0
    load.pri 0x4630
    eq.c.pri -1
    jzer @bots_ia_l138
    push.c 0x0
    call @pw_wander
    load.pri 0x4714
    jzer @bots_ia_l139
    load.pri 0x4718
    stor.pri 0x45e4
    const.pri 0x3f800000
    stor.pri 0x45e0
bots_ia_l139:
    zero.pri
    stack 0x4
    retn
bots_ia_l138:
    stack -12
    zero.pri
    addr.alt -16
    fill 0xc
    push.c 0x1ca0
    push.c 0x4638
    push.adr -16
    sysreq.n floatvecsubto, 3
    stack -4
    push.adr -16
    sysreq.n floatveclength, 1
    stor.s.pri -20
    stack -12
    zero.pri
    addr.alt -32
    fill 0xc
    stack -12
    zero.pri
    addr.alt -44
    fill 0xc
    stack -4
    push.adr -16
    push.c 0x4
    call @pw_yawOf
    stor.s.pri -48
    const.pri 0x3
    load.alt 0x457c
    sdiv.alt
    move.pri
    jzer @bots_ia_l141
    load.pri 0x4634
    load.alt 0x457c
    sub.alt
    const.alt 0x3
    jsless @bots_ia_l141
    zero.pri
    jump @bots_ia_l142
bots_ia_l141:
    const.pri 0x1
bots_ia_l142:
    jzer @bots_ia_l140
    push.c 0x4784
    push.c 0x4778
    push.c 0x8
    call @pw_intercept
    stor.pri 0x4790
bots_ia_l140:
    stack -4
    load.pri 0x4790
    stor.s.pri -52
    addr.alt -32
    const.pri 0x4778
    movs 0xc
    addr.alt -44
    const.pri 0x4784
    movs 0xc
    load.s.pri -52
    jzer @bots_ia_l143
    push.adr -32
    push.c 0x4
    call @pw_yawOf
    stor.s.pri -48
bots_ia_l143:
    stack -4
    push.c 0x0
    call @pw_torpedoRange
    stor.s.pri -56
    stack -4
    push.c 0x0
    call @pw_agile
    jzer @bots_ia_l144
    const.pri 0x44d48000
    jump @bots_ia_l145
bots_ia_l144:
    push.c 0x453b8000
    push.c 0x45098000
    load.s.pri -56
    const.alt 0x3eb33333
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.c 0xc
    call @pw_fclamp
bots_ia_l145:
    stor.s.pri -60
    const.pri 0x3ecccccd
    load.s.alt -4
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l146
    load.pri 0x45c4
    jnz @bots_ia_l148
    load.pri 0x45bc
    load.alt 0x45c0
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgteq_Float_Float
    pop.alt
    jzer @bots_ia_l148
    const.pri 0x455ac000
    load.s.alt -20
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l149
    load.pri 0x4710
    jnz @bots_ia_l149
    zero.pri
    jump @bots_ia_l150
bots_ia_l149:
    const.pri 0x1
bots_ia_l150:
    jzer @bots_ia_l148
    const.pri 0x1
    jump @bots_ia_l151
bots_ia_l148:
    zero.pri
bots_ia_l151:
    jzer @bots_ia_l147
    push.c 0x0
    call @pw_maskerOn
bots_ia_l147:
    load.pri 0x45c4
    jzer @bots_ia_l152
    push.adr -16
    push.c 0x4
    call @pw_yawOf
    const.alt 0x40490fda
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x45e4
    const.pri 0x3f800000
    stor.pri 0x45e0
    push 0x4610
    push.c 0x437a0000
    sysreq.n floatadd, 2
    push.pri
    const.pri 0x1ca0
    add.c 0x4
    load.i
    push.pri
    push.c 0x8
    call @pw_fmin
    stor.pri 0x45ec
    zero.pri
    stack 0x3c
    retn
bots_ia_l152:
    load.s.pri -48
    stor.pri 0x45e4
    load.s.pri -20
    push.pri
    load.s.pri -56
    const.alt 0x3f4ccccd
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l153
    const.pri -1088841318
    jump @bots_ia_l154
bots_ia_l153:
    const.pri 0x3e4ccccd
bots_ia_l154:
    stor.pri 0x45e0
    jump @bots_ia_l155
bots_ia_l146:
    load.pri 0x46c8
    jnz @bots_ia_l156
    push.adr -16
    push.c 0x4
    call @pw_yawOf
    stor.pri 0x45e4
    const.pri 0x3f800000
    stor.pri 0x45e0
    jump @bots_ia_l157
bots_ia_l156:
    load.s.pri -20
    push.pri
    load.s.pri -60
    const.alt 0x442f0000
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l158
    load.s.pri -48
    stor.pri 0x45e4
    const.pri 0x3f800000
    stor.pri 0x45e0
    jump @bots_ia_l159
bots_ia_l158:
    load.s.pri -20
    push.pri
    const.pri 0x447a0000
    load.s.alt -60
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l160
    load.s.pri -48
    stor.pri 0x45e4
    const.pri -1088841318
    stor.pri 0x45e0
    jump @bots_ia_l161
bots_ia_l160:
    load.s.pri -48
    stor.pri 0x45e4
    const.pri 0x3eb33333
    stor.pri 0x45e0
bots_ia_l161:
bots_ia_l159:
bots_ia_l157:
bots_ia_l155:
    load.pri 0x4714
    jzer @bots_ia_l162
    load.pri 0x4718
    stor.pri 0x45e4
    const.pri 0x3f800000
    stor.pri 0x45e0
    jump @bots_ia_l163
bots_ia_l162:
    const.pri 0x4638
    add.c 0x4
    load.i
    push.pri
    const.pri 0x4644
    add.c 0x4
    load.i
    const.alt 0x41f00000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x45ec
bots_ia_l163:
    const.pri 0x44610000
    load.s.alt -20
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l165
    load.pri 0x45e0
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l165
    const.pri 0x1
    jump @bots_ia_l166
bots_ia_l165:
    zero.pri
bots_ia_l166:
    jzer @bots_ia_l164
    const.pri -1090519040
    stor.pri 0x45e0
bots_ia_l164:
    push.s -52
    push.s -20
    push.adr -44
    push.adr -32
    push.c 0x10
    call @pw_fire
    stack 0x3c
    zero.pri
    retn
pw_wander:
    proc
    load.pri 0x4710
    jzer @bots_ia_l168
    const.pri 0x1c80
    add.c 0x8
    load.i
    zero.alt
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatornoteq_Float_Float
    jzer @bots_ia_l168
    const.pri 0x1
    jump @bots_ia_l169
bots_ia_l168:
    zero.pri
bots_ia_l169:
    jzer @bots_ia_l167
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x0
    push.c 0x1c80
    push.adr -12
    sysreq.n actorLocalVectorToWorld, 3
    push.adr -12
    push.c 0x4
    call @pw_yawOf
    stor.pri 0x45e4
    const.pri 0x3f19999a
    stor.pri 0x45e0
    zero.pri
    stack 0xc
    retn
bots_ia_l167:
    load.pri 0x46d8
    jzer @bots_ia_l171
    load.pri 0x46d8
    load.alt 0x457c
    sub.alt
    const.alt 0x258
    jsgeq @bots_ia_l171
    push.c 0x1ca0
    push.c 0x46cc
    push.c 0x8
    call @pw_distance2D
    move.alt
    const.pri 0x44160000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l171
    const.pri 0x1
    jump @bots_ia_l172
bots_ia_l171:
    zero.pri
bots_ia_l172:
    jzer @bots_ia_l170
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x1ca0
    push.c 0x46cc
    push.adr -12
    sysreq.n floatvecsubto, 3
    push.adr -12
    push.c 0x4
    call @pw_yawOf
    stor.pri 0x45e4
    const.pri 0x46cc
    add.c 0x4
    load.i
    stor.pri 0x45ec
    const.pri 0x3f800000
    stor.pri 0x45e0
    zero.pri
    stack 0xc
    retn
bots_ia_l170:
    load.pri 0x46e8
    jzer @bots_ia_l174
    push.c 0x1ca0
    push.c 0x46dc
    push.c 0x8
    call @pw_distance2D
    move.alt
    const.pri 0x44bb8000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l174
    const.pri 0x1
    jump @bots_ia_l175
bots_ia_l174:
    zero.pri
bots_ia_l175:
    jzer @bots_ia_l173
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x1ca0
    push.c 0x46dc
    push.adr -12
    sysreq.n floatvecsubto, 3
    push.adr -12
    push.c 0x4
    call @pw_yawOf
    stor.pri 0x45e4
    const.pri 0x46dc
    add.c 0x4
    load.i
    stor.pri 0x45ec
    const.pri 0x3f800000
    stor.pri 0x45e0
    zero.pri
    stack 0xc
    retn
bots_ia_l173:
    const.pri 0xf0
    load.alt 0x457c
    sdiv.alt
    move.pri
    jnz @bots_ia_l176
    load.pri 0x45e4
    push.pri
    push.c 0x0
    call @pw_frandom
    move.alt
    const.pri 0x3f000000
    push.pri
    push.alt
    sysreq.n floatsub, 2
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x45e4
bots_ia_l176:
    push.c -1005191168
    push 0x4610
    push.c 0x43960000
    sysreq.n floatadd, 2
    push.pri
    push.c 0x8
    call @pw_fmax
    stor.pri 0x45ec
    const.pri 0x3f19999a
    stor.pri 0x45e0
    zero.pri
    retn
pw_agile:
    proc
    load.pri 0x46c4
    load.alt 0x457c
    sub.alt
    const.alt 0x78
    sless
    retn
pw_torpedoRange:
    proc
    load.pri 0x459c
    eq.c.pri 0x1
    jzer @bots_ia_l177
    const.pri 0x45cb2000
    jump @bots_ia_l178
bots_ia_l177:
    load.pri 0x459c
    eq.c.pri 0x2
    jzer @bots_ia_l179
    const.pri 0x4604d000
    jump @bots_ia_l180
bots_ia_l179:
    const.pri 0x461c4000
bots_ia_l180:
bots_ia_l178:
    retn
pw_torpedoRun:
    proc
    push.c 0x3f7d70a4
    push.c 0x3f800000
    sysreq.n floatsub, 2
    const.alt 0x3f99999a
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    const.alt 0x3f7d70a4
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    load.s.pri 0xc
    push.pri
    push.s 0xc
    push.c 0x3f7d70a4
    sysreq.n floatpower, 2
    const.alt 0x3f800000
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x3f7d70a4
    push.c 0x3f800000
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    retn
pw_targetAt:
    proc
    stack -4
    load.s.pri 0xc
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -4
    const.pri 0x4638
    load.s.alt 0x10
    movs 0xc
    load.pri 0x4c3c
    zero.alt
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatoreqeq_Float_Float
    jzer @bots_ia_l181
    load.s.pri 0x10
    push.pri
    load.s.pri 0x10
    load.i
    push.pri
    const.pri 0x4644
    load.i
    move.alt
    load.s.pri -4
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    load.s.pri 0x10
    add.c 0x8
    push.pri
    load.s.pri 0x10
    add.c 0x8
    load.i
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    move.alt
    load.s.pri -4
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    jump @bots_ia_l182
bots_ia_l181:
    stack -4
    load.pri 0x46bc
    push.pri
    load.s.pri -4
    load.alt 0x4650
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -8
    load.s.pri 0x10
    push.pri
    load.s.pri 0x10
    load.i
    push.pri
    load.pri 0x4c3c
    push.pri
    load.pri 0x4c40
    push.pri
    push.c 0x0
    push.s -8
    sysreq.n floatcos, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    load.s.pri 0x10
    add.c 0x8
    push.pri
    load.s.pri 0x10
    add.c 0x8
    load.i
    push.pri
    load.pri 0x4c3c
    push.pri
    push.c 0x0
    push.s -8
    sysreq.n floatsin, 2
    move.alt
    load.pri 0x4c44
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    stack 0x4
bots_ia_l182:
    load.s.pri 0x10
    add.c 0x4
    push.pri
    load.s.pri 0x10
    add.c 0x4
    load.i
    push.pri
    const.pri 0x4644
    add.c 0x4
    load.i
    push.pri
    push.c 0x41c80000
    push.s -4
    push.c 0x8
    call @pw_fmin
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    load.s.pri 0x10
    add.c 0x4
    load.i
    move.alt
    const.pri -1031012352
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l183
    load.s.pri 0x10
    add.c 0x4
    move.alt
    const.pri -1031012352
    stor.i
bots_ia_l183:
    stack 0x4
    zero.pri
    retn
pw_intercept:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.adr -12
    push.c 0x4
    call @pw_tubePosition
    zero 0x4c3c
    load.pri 0x4574
    const.alt 0x2
    jsless @bots_ia_l185
    push 0x4650
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3951b717
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgteq_Float_Float
    pop.alt
    jzer @bots_ia_l185
    const.pri 0x1
    jump @bots_ia_l186
bots_ia_l185:
    zero.pri
bots_ia_l186:
    jzer @bots_ia_l184
    const.pri 0x4644
    load.i
    push.pri
    const.pri 0x4644
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    move.alt
    load.pri 0x4650
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    stor.pri 0x4c3c
    push.c 0x0
    push 0x46bc
    sysreq.n floatcos, 2
    stor.pri 0x4c40
    push.c 0x0
    push 0x46bc
    sysreq.n floatsin, 2
    stor.pri 0x4c44
bots_ia_l184:
    push.c 0x0
    push.c 0x43700000
    stack -12
    zero.pri
    addr.alt -32
    fill 0xc
    push.adr -32
    push.s -20
    push.c 0x8
    call @pw_targetAt
    push.s -20
    push.c 0x4
    call @pw_torpedoRun
    push.pri
    push.adr -12
    push.adr -32
    push.c 0x8
    call @pw_distance
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l187
    zero.pri
    stack 0x20
    retn
bots_ia_l187:
    push.c 0x0
    jump @bots_ia_l190
bots_ia_l188:
    inc.s -36
bots_ia_l190:
    load.s.pri -36
    const.alt 0xc
    jsgeq @bots_ia_l189
    stack -4
    load.s.pri -20
    load.s.alt -16
    push.pri
    push.alt
    sysreq.n floatadd, 2
    const.alt 0x3f000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    stor.s.pri -40
    push.adr -32
    push.s -40
    push.c 0x8
    call @pw_targetAt
    push.s -40
    push.c 0x4
    call @pw_torpedoRun
    push.pri
    push.adr -12
    push.adr -32
    push.c 0x8
    call @pw_distance
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l191
    load.s.pri -40
    stor.s.pri -16
    jump @bots_ia_l192
bots_ia_l191:
    load.s.pri -40
    stor.s.pri -20
bots_ia_l192:
    stack 0x4
    jump @bots_ia_l188
bots_ia_l189:
    stack 0x4
    push.adr -32
    push.s -20
    push.c 0x8
    call @pw_targetAt
    push.s -20
    push.c 0x4
    call @pw_torpedoRun
    push.pri
    push.c 0x0
    call @pw_torpedoRange
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l193
    zero.pri
    stack 0x20
    retn
bots_ia_l193:
    push.adr -12
    push.adr -32
    push.s 0xc
    sysreq.n floatvecsubto, 3
    push.s 0xc
    push.s 0xc
    sysreq.n floatvecnormalize, 2
    load.s.pri 0x10
    push.pri
    addr.pri -32
    pop.alt
    movs 0xc
    push.c 0x2
    push.s -20
    sysreq.n floatround, 2
    add.c 0x1
    stack 0x20
    retn
pw_tubePosition:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x43660000
    push.c -1054867456
    push 0x45c8
    sysreq.n float, 1
    const.alt 0x41700000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.adr -12
    sysreq.n floatvecset, 4
    push.c 0x0
    push.adr -12
    push.s 0xc
    sysreq.n actorLocalPosToWorld, 3
    stack 0xc
    zero.pri
    retn
pw_fire:
    proc
    load.pri 0x45b4
    jnz @bots_ia_l195
    load.pri 0x45c4
    jnz @bots_ia_l195
    push.c 0x4c48
    sysreq.n sysGetGlobal, 1
    jnz @bots_ia_l195
    push.c 0x4c80
    sysreq.n sysGetGlobal, 1
    jnz @bots_ia_l195
    zero.pri
    jump @bots_ia_l196
bots_ia_l195:
    const.pri 0x1
bots_ia_l196:
    jzer @bots_ia_l194
    zero.pri
    retn
bots_ia_l194:
    load.pri 0x45a4
    jnz @bots_ia_l198
    load.pri 0x45b8
    jnz @bots_ia_l198
    const.pri 0x1
    jump @bots_ia_l199
bots_ia_l198:
    zero.pri
bots_ia_l199:
    jzer @bots_ia_l197
    zero.pri
    retn
bots_ia_l197:
    load.pri 0x4634
    load.alt 0x457c
    sub.alt
    const.alt 0x14
    jsless @bots_ia_l201
    load.pri 0x46c8
    jzer @bots_ia_l201
    load.s.pri 0x18
    jzer @bots_ia_l201
    zero.pri
    jump @bots_ia_l202
bots_ia_l201:
    const.pri 0x1
bots_ia_l202:
    jzer @bots_ia_l200
    zero.pri
    retn
bots_ia_l200:
    load.pri 0x4574
    const.alt 0x2
    jsless @bots_ia_l204
    push.c 0x0
    call @pw_agile
    jzer @bots_ia_l204
    load.s.pri 0x18
    const.alt 0x3c
    jsleq @bots_ia_l204
    const.pri 0x44c80000
    load.s.alt 0x14
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l204
    const.pri 0x1
    jump @bots_ia_l205
bots_ia_l204:
    zero.pri
bots_ia_l205:
    jzer @bots_ia_l203
    zero.pri
    retn
bots_ia_l203:
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.adr -12
    push.c 0x4
    call @pw_tubePosition
    stack -4
    load.s.pri 0xc
    load.i
    push.pri
    load.s.pri 0xc
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    load.s.pri 0xc
    add.c 0x8
    load.i
    push.pri
    load.s.pri 0xc
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    stor.s.pri -16
    const.pri 0x3f000000
    load.s.alt -16
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l206
    zero.pri
    stack 0x10
    retn
bots_ia_l206:
    stack -4
    push.s 0xc
    push.c 0x4
    call @pw_yawOf
    stor.s.pri -20
    stack -4
    push.s -16
    load.s.pri 0xc
    add.c 0x4
    load.i
    push.pri
    sysreq.n floatatan2, 2
    stor.s.pri -24
    stack -4
    load.pri 0x1cc8
    load.s.alt -20
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    push.pri
    push.c 0x4
    call @pw_fabs
    stor.s.pri -28
    const.pri 0x3db851ec
    load.s.alt -28
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l208
    push.s -24
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3e99999a
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l208
    zero.pri
    jump @bots_ia_l209
bots_ia_l208:
    const.pri 0x1
bots_ia_l209:
    jzer @bots_ia_l207
    zero.pri
    stack 0x1c
    retn
bots_ia_l207:
    stack -4
    push.adr -12
    push.s 0x10
    push.c 0x8
    call @pw_distance
    stor.s.pri -32
    const.pri 0x43c80000
    load.s.alt -32
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l211
    load.s.pri -32
    push.pri
    push.c 0x0
    call @pw_torpedoRange
    const.alt 0x3f6b851f
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l211
    zero.pri
    jump @bots_ia_l212
bots_ia_l211:
    const.pri 0x1
bots_ia_l212:
    jzer @bots_ia_l210
    zero.pri
    stack 0x20
    retn
bots_ia_l210:
    push.c 0x4784
    push.c 0x4778
    push.c 0x8
    call @pw_intercept
    stor.s.pri 0x18
    load.s.pri 0x18
    jnz @bots_ia_l213
    zero.pri
    stack 0x20
    retn
bots_ia_l213:
    const.pri 0x4778
    load.s.alt 0xc
    movs 0xc
    const.pri 0x4784
    load.s.alt 0x10
    movs 0xc
    push.s 0xc
    push.c 0x4
    call @pw_yawOf
    stor.s.pri -20
    load.s.pri 0xc
    load.i
    push.pri
    load.s.pri 0xc
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    load.s.pri 0xc
    add.c 0x8
    load.i
    push.pri
    load.s.pri 0xc
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    push.pri
    load.s.pri 0xc
    add.c 0x4
    load.i
    push.pri
    sysreq.n floatatan2, 2
    stor.s.pri -24
    load.pri 0x1cc8
    load.s.alt -20
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    push.pri
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3db851ec
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l214
    zero.pri
    stack 0x20
    retn
bots_ia_l214:
    push.c 0x42f00000
    push.s 0x10
    push.adr -12
    push.c 0xc
    call @pw_clearLine
    jnz @bots_ia_l215
    zero.pri
    stack 0x20
    retn
bots_ia_l215:
    push.s 0x10
    push.adr -12
    push.c 0x8
    call @pw_mateInTheWay
    jzer @bots_ia_l216
    zero.pri
    stack 0x20
    retn
bots_ia_l216:
    stack -4
    const.pri 0x4644
    load.i
    push.pri
    const.pri 0x4644
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    push.pri
    const.pri 0x4644
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    push.pri
    push.c 0x0
    load.s.pri -20
    load.alt 0x46bc
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    push.pri
    push.c 0x4
    call @pw_fabs
    push.pri
    sysreq.n floatsin, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    stor.s.pri -36
    load.pri 0x45b8
    jzer @bots_ia_l218
    push 0x4630
    push.c 0x4
    call @pw_isMasked
    jnz @bots_ia_l218
    const.pri 0x44960000
    load.s.alt 0x14
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l218
    const.pri 0x45abe000
    load.s.alt 0x14
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l218
    push 0x4650
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3c449ba6
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l219
    const.pri 0x40c00000
    load.s.alt -36
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l219
    load.pri 0x1c68
    push.pri
    push 0x4588
    push.c 0x3ecccccd
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l219
    load.pri 0x45a4
    jzer @bots_ia_l219
    zero.pri
    jump @bots_ia_l220
bots_ia_l219:
    const.pri 0x1
bots_ia_l220:
    jzer @bots_ia_l218
    const.pri 0x1
    jump @bots_ia_l221
bots_ia_l218:
    zero.pri
bots_ia_l221:
    jzer @bots_ia_l217
    push.s -24
    push.s -20
    push.c 0x8
    call @pw_fireHoming
    dec 0x45b8
    jump @bots_ia_l222
bots_ia_l217:
    load.pri 0x45a4
    jzer @bots_ia_l223
    load.s.pri -20
    push.pri
    push.c 0x0
    call @pw_frandom
    move.alt
    const.pri 0x3f000000
    push.pri
    push.alt
    sysreq.n floatsub, 2
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    load.pri 0x4574
    const.alt 0x4544
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -20
    load.s.pri -24
    push.pri
    push.c 0x0
    call @pw_frandom
    move.alt
    const.pri 0x3f000000
    push.pri
    push.alt
    sysreq.n floatsub, 2
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    load.pri 0x4574
    const.alt 0x4544
    idxaddr.b 0x2
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -24
    push.s -24
    push.s -20
    push.adr -12
    push.c 0xc
    call @pw_fireTorpedo
    load.s.pri -24
    stor.pri 0x4774
    dec 0x45a4
    load.pri 0x45ac
    move.alt
    zero.pri
    jsless @bots_ia_l224
    load.pri 0x45a8
    stor.pri 0x45ac
bots_ia_l224:
    jump @bots_ia_l225
bots_ia_l223:
    zero.pri
    stack 0x24
    retn
bots_ia_l225:
bots_ia_l222:
    load.pri 0x45b0
    push.pri
    load.pri 0x4574
    const.alt 0x4534
    idxaddr.b 0x2
    load.i
    pop.alt
    add
    stor.pri 0x45b4
    load.pri 0x45c8
    neg
    stor.pri 0x45c8
    stack 0x24
    zero.pri
    retn
pw_mateInTheWay:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.s 0xc
    push.s 0x10
    push.adr -12
    sysreq.n floatvecsubto, 3
    stack -4
    push.adr -12
    sysreq.n floatveclength, 1
    stor.s.pri -16
    const.pri 0x3f800000
    load.s.alt -16
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l226
    zero.pri
    stack 0x10
    retn
bots_ia_l226:
    load.s.pri -16
    const.alt 0x3f800000
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    push.pri
    push.adr -12
    sysreq.n floatvecscale, 2
    push.c 0x0
    jump @bots_ia_l229
bots_ia_l227:
    inc.s -20
bots_ia_l229:
    load.s.pri -20
    load.alt 0x470c
    jsgeq @bots_ia_l228
    stack -12
    zero.pri
    addr.alt -32
    fill 0xc
    const.alt 0x46ec
    load.s.pri -20
    lidx.b 0x2
    push.pri
    push.adr -32
    sysreq.n actorGetPosition, 2
    jnz @bots_ia_l230
    stack 0xc
    jump @bots_ia_l227
bots_ia_l230:
    stack -12
    zero.pri
    addr.alt -44
    fill 0xc
    push.s 0xc
    push.adr -32
    push.adr -44
    sysreq.n floatvecsubto, 3
    stack -4
    push.adr -12
    push.adr -44
    sysreq.n floatvecdot, 2
    stor.s.pri -48
    const.pri -1027080192
    load.s.alt -48
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l232
    load.s.pri -48
    push.pri
    load.s.pri -16
    const.alt 0x43480000
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jnz @bots_ia_l232
    zero.pri
    jump @bots_ia_l233
bots_ia_l232:
    const.pri 0x1
bots_ia_l233:
    jzer @bots_ia_l231
    stack 0x1c
    jump @bots_ia_l227
bots_ia_l231:
    push.s -48
    push.c 0x4
    call @pw_operatorsub_Float
    push.pri
    push.adr -12
    push.adr -44
    sysreq.n floatvecaddscale, 3
    push.adr -44
    sysreq.n floatveclength, 1
    move.alt
    const.pri 0x435c0000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l234
    const.pri 0x1
    stack 0x30
    retn
bots_ia_l234:
    stack 0x1c
    jump @bots_ia_l227
bots_ia_l228:
    stack 0x4
    zero.pri
    stack 0x10
    retn
pw_spawn:
    proc
    stack -4
    sysreq.n worldNewActor, 0
    stor.s.pri -4
    push.s -4
    push.s 0xc
    sysreq.n actorReadProperties, 2
    push.s -4
    push.s 0x10
    sysreq.n actorSetPosition, 2
    load.s.pri -4
    stack 0x4
    retn
pw_arm:
    proc
    push.s 0xc
    push 0x4580
    sysreq.n actorSetParent, 2
    push.s 0xc
    push.c 0x0
    sysreq.n actorSetIdleDistance, 2
    push.s 0xc
    push.c 0x1
    push.c 0x4cc0
    sysreq.n actorSetPropInt, 3
    push.s 0xc
    push.c 0x1
    push.c 0x4cf0
    sysreq.n actorSetPropInt, 3
    push.s 0xc
    push.c 0x1
    push.c 0x4d08
    sysreq.n actorSetPropInt, 3
    push.s 0xc
    push 0x4580
    push.c 0x4d18
    sysreq.n actorSetPropInt, 3
    push.s 0xc
    push 0x4584
    push.c 0x4d3c
    sysreq.n actorSetPropInt, 3
    push.s 0xc
    push.c 0x1
    push.c 0x4d64
    sysreq.n actorSetPropInt, 3
    zero.pri
    retn
pw_fireTorpedo:
    proc
    stack -128
    zero.pri
    addr.alt -128
    fill 0x80
    push.c 0x459c
    push.c 0x4d84
    push.c 0x0
    push.c 0x20
    push.adr -128
    sysreq.n strformat, 5
    stack -4
    push.s 0xc
    push.adr -128
    push.c 0x8
    call @pw_spawn
    stor.s.pri -132
    push.s -132
    push.c 0x4
    call @pw_arm
    push.s -132
    push.s 0x10
    push.c 0x4de0
    sysreq.n actorSetPropReal, 3
    push.s 0x14
    push.s 0x10
    push.s -132
    push.c 0xc
    call @pw_orient
    stack 0x84
    zero.pri
    retn
pw_orient:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x0
    push.s 0x10
    push.s 0x14
    push.c 0x4
    call @pw_operatorsub_Float
    push.pri
    push.adr -12
    sysreq.n floatvecset, 4
    push.s 0xc
    push.adr -12
    sysreq.n actorSetRotation, 2
    push.s 0xc
    sysreq.n actorUpdateMatrix, 1
    stack -12
    zero.pri
    addr.alt -24
    fill 0xc
    push.s 0xc
    push.adr -24
    push.c 0x2
    sysreq.n actorGetAxis, 3
    push.s 0x14
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3b03126f
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l236
    addr.pri -24
    add.c 0x4
    load.i
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    push.pri
    load.s.pri 0x14
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    pop.alt
    jeq @bots_ia_l236
    const.pri 0x1
    jump @bots_ia_l237
bots_ia_l236:
    zero.pri
bots_ia_l237:
    jzer @bots_ia_l235
    addr.alt -12
    load.s.pri 0x14
    stor.i
    push.s 0xc
    push.adr -12
    sysreq.n actorSetRotation, 2
    push.s 0xc
    sysreq.n actorUpdateMatrix, 1
bots_ia_l235:
    stack 0x18
    zero.pri
    retn
pw_fireHoming:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.adr -12
    push.c 0x4
    call @pw_tubePosition
    stack -4
    push.adr -12
    push.c 0x4e00
    push.c 0x8
    call @pw_spawn
    stor.s.pri -16
    push.s -16
    push.c 0x4
    call @pw_arm
    push.s 0x10
    push.s 0xc
    push.s -16
    push.c 0xc
    call @pw_orient
    push.s -16
    push.c 0x1
    push.c 0x4e64
    sysreq.n actorSetPropInt, 3
    push.c 0x4630
    push.c 0x4e88
    push.s -16
    sysreq.n sysCallPublic, 3
    stack 0x10
    zero.pri
    retn
pw_maskerOn:
    proc
    push 0x45bc
    push 0x45c0
    sysreq.n floatsub, 2
    stor.pri 0x45c0
    const.pri 0x12c
    stor.pri 0x45c4
    push.c 0x0
    push.c 0x1
    push.c 0x4ec0
    sysreq.n actorSetPropInt, 3
    push.c 0x0
    push.c 0x1
    push.c 0x4edc
    sysreq.n actorSetPropInt, 3
    zero.pri
    retn
pw_maskerOff:
    proc
    zero 0x45c4
    push.c 0x0
    push.c 0x0
    push.c 0x4f04
    sysreq.n actorSetPropInt, 3
    push.c 0x0
    push.c 0x0
    push.c 0x4f20
    sysreq.n actorSetPropInt, 3
    zero.pri
    retn
pw_steerClear:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.c 0x0
    push.c -1082130432
    push.c 0x0
    push.adr -12
    sysreq.n floatvecset, 4
    const.pri 0x1ca0
    add.c 0x4
    load.i
    push.pri
    push.c 0x1
    push.c 0x457a0000
    push.adr -12
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    stor.pri 0x4610
    stack -4
    const.pri 0x45cc
    load.i
    push.pri
    const.pri 0x45cc
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    stor.s.pri -16
    stack -4
    load.s.pri -16
    const.alt 0x42480000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    const.alt 0x43fa0000
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -20
    stack -12
    zero.pri
    addr.alt -32
    fill 0xc
    load.pri 0x4624
    jzer @bots_ia_l238
    push 0x4628
    push 0x1cc8
    sysreq.n floatadd, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x45e8
    zero.pri
    stack 0x20
    retn
bots_ia_l238:
    load.pri 0x45e0
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l239
    push 0x1cc8
    push.c 0x40490fda
    sysreq.n floatadd, 2
    push.pri
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    push.c 0x1
    push.c 0x43e10000
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    move.alt
    const.pri 0x43e10000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l240
    const.pri 0x3e99999a
    stor.pri 0x45e0
bots_ia_l240:
    load.pri 0x45e4
    stor.pri 0x45e8
    zero.pri
    stack 0x20
    retn
bots_ia_l239:
    stack -24
    const.pri 0x4f48
    addr.alt -56
    movs 0x18
    push.c -1082130432
    stack -4
    load.pri 0x45e4
    stor.s.pri -64
    load.pri 0x462c
    jnz @bots_ia_l241
    push.c 0x0
    push.c 0x0
    push 0x45e4
    push.c 0x3f4ccccd
    sysreq.n floatadd, 2
    push.pri
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    push.c 0x1
    load.s.pri -20
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    stor.s.pri -68
    push.c 0x3f4ccccd
    push 0x45e4
    sysreq.n floatsub, 2
    push.pri
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    push.c 0x1
    load.s.pri -20
    const.alt 0x40000000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    stor.s.pri -72
    load.s.pri -72
    load.s.alt -68
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgteq_Float_Float
    pop.alt
    jzer @bots_ia_l242
    const.pri 0x1
    jump @bots_ia_l243
bots_ia_l242:
    const.pri -1
bots_ia_l243:
    stor.pri 0x462c
    stack 0x8
bots_ia_l241:
    push.c 0x0
    push.c 0x0
    jump @bots_ia_l246
bots_ia_l244:
    inc.s -72
bots_ia_l246:
    load.s.pri -72
    const.alt 0x2
    jsgeq @bots_ia_l247
    load.s.pri -68
    jnz @bots_ia_l247
    const.pri 0x1
    jump @bots_ia_l248
bots_ia_l247:
    zero.pri
bots_ia_l248:
    jzer @bots_ia_l245
    stack -4
    load.s.pri -72
    jnz @bots_ia_l249
    load.pri 0x462c
    jump @bots_ia_l250
bots_ia_l249:
    load.pri 0x462c
    neg
bots_ia_l250:
    push.pri
    sysreq.n float, 1
    stor.s.pri -76
    stack -4
    load.s.pri -72
    stor.s.pri -80
    jump @bots_ia_l253
bots_ia_l251:
    inc.s -80
bots_ia_l253:
    load.s.pri -80
    const.alt 0x6
    jsgeq @bots_ia_l252
    stack -4
    load.pri 0x45e4
    push.pri
    addr.alt -56
    load.s.pri -80
    lidx.b 0x2
    move.alt
    load.s.pri -76
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.s.pri -84
    push.s -84
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    stack -4
    push.c 0x1
    push.s -20
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    stor.s.pri -88
    load.s.pri -20
    load.s.alt -88
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgteq_Float_Float
    pop.alt
    jzer @bots_ia_l254
    addr.pri -32
    add.c 0x4
    move.alt
    const.pri -1095552205
    stor.i
    push.adr -32
    push.adr -32
    sysreq.n floatvecnormalize, 2
    push.c 0x1
    load.s.pri -20
    const.alt 0x3f333333
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    push.pri
    load.s.pri -20
    const.alt 0x3f333333
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l255
    const.pri 0x1ca0
    add.c 0x4
    load.i
    const.alt 0x43480000
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    push 0x45ec
    push.c 0x8
    call @pw_fmax
    stor.pri 0x45ec
bots_ia_l255:
    load.s.pri -84
    stor.s.pri -64
    load.s.pri -88
    stor.s.pri -60
    const.pri 0x1
    stor.s.pri -68
    load.s.pri -80
    jnz @bots_ia_l256
    zero 0x462c
bots_ia_l256:
    stack 0x8
    jump @bots_ia_l252
bots_ia_l254:
    load.s.pri -60
    load.s.alt -88
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l257
    load.s.pri -88
    stor.s.pri -60
    load.s.pri -84
    stor.s.pri -64
bots_ia_l257:
    stack 0x8
    jump @bots_ia_l251
bots_ia_l252:
    stack 0x4
    stack 0x4
    jump @bots_ia_l244
bots_ia_l245:
    stack 0x4
    push.s -64
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x45e8
    push 0x1cc8
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    push.c 0x1
    push.c 0x43960000
    push.adr -32
    push.c 0x1ca0
    sysreq.n worldClipLine, 4
    move.alt
    const.pri 0x43960000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l259
    const.pri 0x437a0000
    load.s.alt -60
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jnz @bots_ia_l259
    zero.pri
    jump @bots_ia_l260
bots_ia_l259:
    const.pri 0x1
bots_ia_l260:
    jzer @bots_ia_l258
    push.c 0x3e19999a
    push 0x45e0
    push.c 0x8
    call @pw_fmin
    stor.pri 0x45e0
bots_ia_l258:
    stack 0x44
    zero.pri
    retn
pw_move:
    proc
    inc 0x4620
    load.pri 0x4620
    const.alt 0x3c
    jsless @bots_ia_l261
    zero 0x4620
    load.pri 0x4624
    jnz @bots_ia_l263
    push 0x45dc
    push.c 0x4
    call @pw_fabs
    move.alt
    const.pri 0x3e99999a
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l263
    push.c 0x1ca0
    push.c 0x4614
    push.c 0x8
    call @pw_distance
    move.alt
    const.pri 0x43160000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l263
    const.pri 0x1
    jump @bots_ia_l264
bots_ia_l263:
    zero.pri
bots_ia_l264:
    jzer @bots_ia_l262
    const.pri 0x32
    stor.pri 0x4624
    push.c 0x0
    call @pw_frandom
    move.alt
    const.pri 0x3f000000
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l265
    const.pri 0x3f99999a
    jump @bots_ia_l266
bots_ia_l265:
    const.pri -1080452710
bots_ia_l266:
    stor.pri 0x4628
bots_ia_l262:
    const.pri 0x4614
    move.alt
    const.pri 0x1ca0
    movs 0xc
bots_ia_l261:
    load.pri 0x4624
    jzer @bots_ia_l267
    load.pri 0x45dc
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l268
    const.pri -1088841318
    jump @bots_ia_l269
bots_ia_l268:
    const.pri 0x3f4ccccd
bots_ia_l269:
    stor.pri 0x45e0
bots_ia_l267:
    load.pri 0x45dc
    push.pri
    push.c 0x3d4ccccd
    push.c -1119040307
    push 0x45dc
    push 0x45e0
    sysreq.n floatsub, 2
    push.pri
    push.c 0xc
    call @pw_fclamp
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x45dc
    push.c 0x3f800000
    push.c -1088841318
    push 0x45dc
    push.c 0xc
    call @pw_fclamp
    stor.pri 0x45dc
    stack -4
    const.pri 0x45cc
    load.i
    push.pri
    const.pri 0x45cc
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    push.pri
    sysreq.n floatsqroot, 1
    stor.s.pri -4
    stack -4
    push.c 0x3ecccccd
    const.pri 0x41200000
    load.s.alt -4
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    push.pri
    push.c 0x8
    call @pw_fmax
    stor.s.pri -8
    stack -4
    load.s.pri -8
    load.alt 0x4590
    push.pri
    push.alt
    sysreq.n floatmul, 2
    stor.s.pri -12
    stack -4
    push 0x1cc8
    push 0x45e8
    sysreq.n floatsub, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.s.pri -16
    push.c 0x0
    load.pri 0x45d8
    load.s.alt -16
    push.pri
    push.alt
    sysreq.n floatmul, 2
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l271
    push.s -16
    push.c 0x4
    call @pw_fabs
    push.pri
    push 0x45d8
    push.c 0x4
    call @pw_fabs
    const.alt 0x41d00000
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlteq_Float_Float
    pop.alt
    jzer @bots_ia_l271
    const.pri 0x1
    jump @bots_ia_l272
bots_ia_l271:
    zero.pri
bots_ia_l272:
    jzer @bots_ia_l270
    zero.s -20
    jump @bots_ia_l273
bots_ia_l270:
    push.c 0x3f800000
    push.c -1082130432
    const.pri 0x3df5c28f
    load.s.alt -16
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    push.pri
    push.c 0xc
    call @pw_fclamp
    stor.s.pri -20
bots_ia_l273:
    load.pri 0x45d8
    push.pri
    load.s.pri -20
    zero.alt
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatornoteq_Float_Float
    jzer @bots_ia_l274
    const.pri 0x3d1ba5e3
    jump @bots_ia_l275
bots_ia_l274:
    const.pri 0x3ca3d70a
bots_ia_l275:
    push.pri
    load.s.pri -20
    load.s.alt -12
    push.pri
    push.alt
    sysreq.n floatmul, 2
    move.alt
    load.pri 0x45d8
    push.pri
    push.alt
    sysreq.n floatsub, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x45d8
    push 0x45d8
    push 0x1cc8
    sysreq.n floatadd, 2
    push.pri
    push.c 0x4
    call @pw_wrapAngle
    stor.pri 0x1cc8
    stack -12
    zero.pri
    addr.alt -32
    fill 0xc
    push 0x1cc8
    push.adr -32
    push.c 0x8
    call @pw_headingOf
    const.pri 0x45cc
    push.pri
    const.pri 0x45cc
    load.i
    push.pri
    const.pri 0x45cc
    load.i
    const.alt 0x3d1ba5e3
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    addr.pri -32
    load.i
    move.alt
    load.pri 0x45dc
    push.pri
    push.alt
    sysreq.n floatmul, 2
    move.alt
    load.pri 0x4594
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    const.pri 0x45cc
    add.c 0x8
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    push.pri
    const.pri 0x45cc
    add.c 0x8
    load.i
    const.alt 0x3d1ba5e3
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    addr.pri -32
    add.c 0x8
    load.i
    move.alt
    load.pri 0x45dc
    push.pri
    push.alt
    sysreq.n floatmul, 2
    move.alt
    load.pri 0x4594
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    stack -4
    push.c 0x41f00000
    push.c -1031012352
    sysreq.n floatsub, 2
    push.pri
    push.c -962838528
    push 0x4610
    push.c 0x430c0000
    sysreq.n floatadd, 2
    push.pri
    push.c 0x8
    call @pw_fmax
    push.pri
    push 0x45ec
    push.c 0xc
    call @pw_fclamp
    stor.s.pri -36
    const.pri 0x45cc
    add.c 0x4
    push.pri
    const.pri 0x45cc
    add.c 0x4
    load.i
    push.pri
    const.pri 0x45cc
    add.c 0x4
    load.i
    const.alt 0x3e23d70a
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    push.pri
    push.c 0x3f800000
    push.c -1082130432
    load.s.pri -36
    push.pri
    const.pri 0x1ca0
    add.c 0x4
    load.i
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    const.alt 0x3c23d70a
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.c 0xc
    call @pw_fclamp
    move.alt
    load.pri 0x4598
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    pop.alt
    stor.i
    load.pri 0x460c
    jzer @bots_ia_l276
    stack -4
    push.c 0x4600
    push.c 0x45cc
    sysreq.n floatvecdot, 2
    stor.s.pri -40
    load.s.pri -40
    move.alt
    zero.pri
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorlt_Float_Float
    pop.alt
    jzer @bots_ia_l277
    push.s -40
    push.c 0x4
    call @pw_operatorsub_Float
    const.alt 0x3fa66666
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.c 0x4600
    push.c 0x45cc
    sysreq.n floatvecaddscale, 3
bots_ia_l277:
    stack 0x4
bots_ia_l276:
    stack -4
    push.c 0x45f4
    sysreq.n floatveclength, 1
    stor.s.pri -40
    const.pri 0x41900000
    load.s.alt -40
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l278
    load.s.pri -40
    const.alt 0x41900000
    push.pri
    push.alt
    sysreq.n floatdiv, 2
    push.pri
    push.c 0x45f4
    sysreq.n floatvecscale, 2
bots_ia_l278:
    push.c 0x45cc
    push.c 0x1ca0
    sysreq.n floatvecadd, 2
    push.c 0x45f4
    push.c 0x1ca0
    sysreq.n floatvecadd, 2
    push.c 0x45f4
    sysreq.n floatveczero, 1
    const.pri 0x1ca0
    add.c 0x4
    load.i
    move.alt
    const.pri -1031012352
    push.pri
    push.pri
    push.alt
    push.c 0x8
    call @pw_operatorgt_Float_Float
    pop.alt
    jzer @bots_ia_l279
    const.pri 0x1ca0
    add.c 0x4
    move.alt
    const.pri -1031012352
    stor.i
bots_ia_l279:
    push 0x1c74
    push 0x1e7c
    sysreq.n floatadd, 2
    stor.pri 0x1e7c
    push 0x1c74
    push.c 0x3f4ccccd
    sysreq.n floatmul, 2
    push.pri
    push 0x1e7c
    push.c 0x3ca3d70a
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatsub, 2
    stor.pri 0x1c74
    load.pri 0x45f0
    push.pri
    push.c 0x3df5c28f
    push.c -1107967345
    const.pri 0x45cc
    add.c 0x4
    load.i
    push.pri
    push.c 0x4
    call @pw_operatorsub_Float
    const.alt 0x3d23d70a
    push.pri
    push.alt
    sysreq.n floatmul, 2
    push.pri
    push.c 0xc
    call @pw_fclamp
    move.alt
    load.pri 0x45f0
    push.pri
    push.alt
    sysreq.n floatsub, 2
    const.alt 0x3dcccccd
    push.pri
    push.alt
    sysreq.n floatmul, 2
    pop.alt
    push.pri
    push.alt
    sysreq.n floatadd, 2
    stor.pri 0x45f0
    load.pri 0x45f0
    stor.pri 0x1e78
    push.c 0x0
    push 0x1e7c
    sysreq.n actorSetRoll, 2
    push.c 0x0
    push 0x1cc8
    sysreq.n actorSetYaw, 2
    push.c 0x0
    push 0x1e78
    sysreq.n actorSetPitch, 2
    push.c 0x0
    push.c 0x45cc
    sysreq.n actorSetVelocity, 2
    stack -12
    zero.pri
    addr.alt -52
    fill 0xc
    push.c 0x0
    push.adr -52
    sysreq.n actorGetRotation, 2
    stack -12
    zero.pri
    addr.alt -64
    fill 0xc
    push.c 0x3070
    push.adr -52
    push.adr -64
    sysreq.n floatvecsubto, 3
    push.c 0x0
    push.adr -64
    sysreq.n actorSetTorque, 2
    const.pri 0x3064
    move.alt
    const.pri 0x45cc
    movs 0xc
    const.pri 0x3070
    push.pri
    addr.pri -52
    pop.alt
    movs 0xc
    push.c 0x0
    push.c 0x1ca0
    sysreq.n actorSetPosition, 2
    load.pri 0x45dc
    stor.pri 0x11f0
    push.c 0x0
    push 0x45dc
    push.c 0x4f60
    sysreq.n actorSetPropReal, 3
    stack 0x40
    zero.pri
    retn
