; Generated by tools/pawn2pasm.py from src/colours.p: edit the source, then run
;   tools/pawn2pasm.py --version v5200 mods/premium/src/colours.p
; Target: amx/mode_title.amx of the update v5200 (addresses of v0 translated by tools/amxport.py; the names g_<hex> of the source are those of v0).

.data_at 0x18afc
.heapstack 0x4000                ; room for the stack of the code below (// @heapstack)
.cells $pawn_data 0x73, 0x61, 0x76, 0x65, 0x2e, 0x73, 0x64, 0x73, 0x77, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73
.cells $pawn_data1 0x0, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x73, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72
.cells $pawn_data2 0x6e, 0x2e, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x0, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x6c
.cells $pawn_data3 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x0, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x73, 0x75, 0x62, 0x2e
.cells $pawn_data4 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x25, 0x64, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x25
.cells $pawn_data5 0x64, 0x0, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x5f, 0x25, 0x30, 0x32, 0x64, 0x0, 0x73
.cells $pawn_data6 0x61, 0x76, 0x65, 0x2e, 0x73, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x25
.cells $pawn_data7 0x64, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x25, 0x64, 0x0, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x73
.cells $pawn_data8 0x64, 0x73, 0x77, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x0, 0x6d, 0x6f, 0x64, 0x65, 0x2e
.cells $pawn_data9 0x73, 0x61, 0x76, 0x65, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x62, 0x0

; ---- hand-written: hooks into the game's code ----
; Start of the title: right after sysDLCUpdateCondition(), where the mod unlocks everything.
.hook 0x114d8
    .original
    push.c 0
    call @pw_sdswPatternColors
    .return

; ---- compiled ----
pw_sdswPatternColors:
    proc
    push.c 0x18afc
    sysreq.n sysGetGlobal, 1
    jzer @colours_l0
    zero.pri
    retn
colours_l0:
    stack -128
    zero.pri
    addr.alt -128
    fill 0x80
    push.c 0x0
    push.c 0x20
    push.adr -128
    push.c 0x18b40
    sysreq.n sysGetGlobalArray, 4
    stack -4
    sysreq.n worldNewActor, 0
    stor.s.pri -132
    push.s -132
    push.c 0x18ba0
    sysreq.n actorReadProperties, 2
    stack -384
    zero.pri
    addr.alt -516
    fill 0x180
    push.c 0x1
    jump @colours_l3
colours_l1:
    inc.s -520
colours_l3:
    load.s.pri -520
    const.alt 0x20
    jsgeq @colours_l2
    addr.alt -128
    load.s.pri -520
    lidx.b 0x2
    jnz @colours_l4
    jump @colours_l1
colours_l4:
    push.c 0x0
    push.c 0x0
    jump @colours_l7
colours_l5:
    inc.s -528
colours_l7:
    load.s.pri -528
    const.alt 0x3
    jsgeq @colours_l6
    push.adr -528
    push.adr -520
    push.c 0x18bd8
    push.c 0x0
    push.c 0x60
    push.adr -516
    sysreq.n strformat, 6
    push.adr -516
    sysreq.n sysGetGlobal, 1
    jzer @colours_l8
    const.pri 0x1
    stor.s.pri -524
colours_l8:
    jump @colours_l5
colours_l6:
    stack 0x4
    load.s.pri -524
    jzer @colours_l9
    stack 0x4
    jump @colours_l1
colours_l9:
    stack -16
    zero.pri
    addr.alt -540
    fill 0x10
    load.s.pri -520
    add.c -1
    heap 0x4
    stor.i
    push.alt
    push.c 0x18c44
    push.c 0x0
    push.c 0x60
    push.adr -516
    sysreq.n strformat, 5
    heap -4
    push.s -132
    push.adr -540
    push.adr -516
    sysreq.n actorGetPropRGB, 3
    push.c 0x0
    jump @colours_l12
colours_l10:
    inc.s -544
colours_l12:
    load.s.pri -544
    const.alt 0x3
    jsgeq @colours_l11
    push.adr -544
    push.adr -520
    push.c 0x18c78
    push.c 0x0
    push.c 0x60
    push.adr -516
    sysreq.n strformat, 6
    addr.alt -540
    load.s.pri -544
    lidx.b 0x2
    push.pri
    push.adr -516
    sysreq.n sysSetGlobal, 2
    jump @colours_l10
colours_l11:
    stack 0x4
    stack 0x14
    jump @colours_l1
colours_l2:
    stack 0x4
    push.s -132
    sysreq.n actorKill, 1
    push.c 0x1
    push.c 0x18ce4
    sysreq.n sysSetGlobal, 2
    push.c 0x1
    push.c 0x18d28
    sysreq.n sysSetGlobal, 2
    zero.pri
    stack 0x204
    retn
