; Generated by tools/amxport.py from bots_hud.pasm (v0) for v5200: edit bots_hud.pasm or v5200.toml, then run
;   tools/amxport.py hud --pasm mods/online/bots_hud.pasm mods/online/bots_hud-v5200.pasm --overrides mods/online/v5200.toml
; hud: the team counters (top right) count the bots afloat with the players, against the server's bots
; (bots.alive1, bots.alive2: bots_battle.pasm, bots_game_state.pasm).

.heapstack 0x4000                   ; 16 KB of heap and stack, as the game's scripts (v5200's: 8 KB)

; @setTeamCount(team, count): count += bots afloat of the team.
.hook 0x58bc
    push.c "server.bots"
    sysreq.n sysGetGlobal, 1
    jzer @count_original
    load.s.pri 12
    eq.c.pri 1
    jzer @count_red
    push.c "bots.alive1"
    jump @count_get
count_red:
    push.c "bots.alive2"
count_get:
    sysreq.n sysGetGlobal, 1
    load.s.alt 16
    add
    stor.s.pri 16
count_original:
    .original
    .return
