; Generated by tools/pawn2pasm.py from src/bots_game_state.p: edit the source, then run
;   tools/pawn2pasm.py mods/online/src/bots_game_state.p
; Target: amx/game_state.amx.

.data_at 0x8dac
.heapstack 0x4000                ; room for the stack of the code below (// @heapstack)
.cells $pawn_data 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x0, 0x62, 0x6f, 0x74, 0x73
.cells $pawn_data1 0x2e, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x31, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x61, 0x6c, 0x69
.cells $pawn_data2 0x76, 0x65, 0x32, 0x0, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x2e
.cells $pawn_data3 0x6e, 0x61, 0x6d, 0x65, 0x25, 0x64, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x25, 0x78
.cells $pawn_data4 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x25, 0x78, 0x2e
.cells $pawn_data5 0x74, 0x65, 0x61, 0x6d, 0x0, 0x40, 0x6b, 0x69, 0x6c, 0x6c, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e
.cells $pawn_data6 0x68, 0x69, 0x74, 0x2e, 0x25, 0x78, 0x2e, 0x25, 0x64, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x68
.cells $pawn_data7 0x69, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x25, 0x78, 0x2e, 0x25, 0x64, 0x0, 0x62, 0x6f, 0x74
.cells $pawn_data8 0x73, 0x2e, 0x68, 0x69, 0x74, 0x62, 0x79, 0x2e, 0x25, 0x78, 0x2e, 0x25, 0x64, 0x0, 0x62, 0x6f
.cells $pawn_data9 0x74, 0x73, 0x2e, 0x68, 0x69, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x25, 0x78, 0x2e, 0x25, 0x64
.cells $pawn_data10 0x0, 0x40, 0x70, 0x75, 0x73, 0x68, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x48, 0x69, 0x74, 0x4d
.cells $pawn_data11 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x0, 0x40, 0x68, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x48, 0x69
.cells $pawn_data12 0x74, 0x0, 0x40, 0x68, 0x69, 0x74, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x6c, 0x61, 0x73, 0x74
.cells $pawn_data13 0x68, 0x69, 0x74, 0x2e, 0x25, 0x78, 0x0, 0x40, 0x70, 0x75, 0x73, 0x68, 0x48, 0x69, 0x74, 0x42
.cells $pawn_data14 0x79, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x0
.cells $pawn_data15 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x0, 0x62, 0x6f, 0x74, 0x73
.cells $pawn_data16 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x68, 0x69, 0x74, 0x2e, 0x25, 0x78, 0x0, 0x62, 0x6f, 0x74, 0x73
.cells $pawn_data17 0x2e, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x31, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x61, 0x6c, 0x69
.cells $pawn_data18 0x76, 0x65, 0x32, 0x0, 0x40, 0x73, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x75, 0x6e
.cells $pawn_data19 0x74, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x68, 0x69, 0x74, 0x62, 0x79, 0x2e, 0x25, 0x78, 0x2e
.cells $pawn_data20 0x25, 0x64, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x25, 0x78, 0x2e, 0x6e, 0x61, 0x6d
.cells $pawn_data21 0x65, 0x0, 0x73, 0x75, 0x62, 0x5f, 0x73, 0x75, 0x6e, 0x6b, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65
.cells $pawn_data22 0x72, 0x2e, 0x65, 0x78, 0x69, 0x74, 0x0, 0x40, 0x64, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x0, 0x73
.cells $pawn_data23 0x63, 0x63, 0x63, 0x73, 0x63, 0x63, 0x63, 0x63, 0x0, 0x4c, 0x4f, 0x47, 0x5f, 0x4e, 0x4f, 0x52
.cells $pawn_data24 0x4d, 0x41, 0x4c, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x68, 0x69, 0x74, 0x2e, 0x25, 0x78, 0x2e
.cells $pawn_data25 0x25, 0x64, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x68, 0x69, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x2e
.cells $pawn_data26 0x25, 0x78, 0x2e, 0x25, 0x64, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x68, 0x69, 0x74, 0x74, 0x69
.cells $pawn_data27 0x6d, 0x65, 0x2e, 0x25, 0x78, 0x2e, 0x25, 0x64, 0x0

; ---- hand-written: hooks into the game's code ----
; checkGameOverTeamBattle: getTeamPlayerCount(team) (func_3fec) -> teamRemaining(team), at both calls.
.hook 0x6854
    call @pw_teamRemaining
    .return

.hook 0x68bc
    call @pw_teamRemaining
    .return

; ---- compiled ----
pw_teamRemaining:
    proc
    stack -4
    push.s 0xc
    push.c 0x4
    call 0x3fec
    stor.s.pri -4
    push.c 0x8dac
    sysreq.n sysGetGlobal, 1
    jzer @bots_game_state_l14
    load.s.pri -4
    push.pri
    load.s.pri 0xc
    eq.c.pri 0x1
    jzer @bots_game_state_l15
    const.pri 0x8ddc
    jump @bots_game_state_l16
bots_game_state_l15:
    const.pri 0x8e0c
bots_game_state_l16:
    push.pri
    sysreq.n sysGetGlobal, 1
    pop.alt
    add
    stor.s.pri -4
bots_game_state_l14:
    load.s.pri -4
    stack 0x4
    retn
pw_botAsPlayer:
    proc
    stack -192
    zero.pri
    addr.alt -192
    fill 0xc0
    stack -384
    zero.pri
    addr.alt -576
    fill 0x180
    stack -4
    load.s.pri 0xc
    add.c 0x7b070000
    stor.s.pri -580
    push.adr 0xc
    push.c 0x8e3c
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 5
    push.c 0x0
    push.c 0x60
    push.adr -576
    push.adr -192
    sysreq.n sysGetGlobalArray, 4
    push.adr -580
    push.c 0x8e88
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 5
    push.c 0x0
    push.c 0x60
    push.adr -576
    push.adr -192
    sysreq.n sysSetGlobalArray, 4
    load.s.pri 0x10
    jzer @bots_game_state_l17
    push.adr -580
    push.c 0x8ec4
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 5
    push.s 0x10
    push.adr -192
    sysreq.n sysSetGlobal, 2
bots_game_state_l17:
    load.s.pri -580
    stack 0x244
    retn
.public @botJoin
pw_at_botJoin:
    proc
    push.s 0x10
    push.s 0xc
    push.c 0x8
    call @pw_botAsPlayer
    zero.pri
    retn
.public @botTakesItem
pw_at_botTakesItem:
    proc
    stack -12
    zero.pri
    addr.alt -12
    fill 0xc
    push.s 0x14
    push.s 0x10
    push.s 0xc
    push.adr -12
    sysreq.n floatvecset, 4
    stack -16
    zero.pri
    addr.alt -28
    fill 0x10
    stack -4
    push.c 0x4
    push.c 0x100
    push.c 0x43c80000
    push.adr -12
    push.adr -28
    sysreq.n worldFindActors, 5
    stor.s.pri -32
    push.c 0x0
    jump @bots_game_state_l20
bots_game_state_l18:
    inc.s -36
bots_game_state_l20:
    load.s.pri -36
    load.s.alt -32
    jsgeq @bots_game_state_l19
    push.c 0x8f00
    addr.alt -28
    load.s.pri -36
    lidx.b 0x2
    push.pri
    sysreq.n sysCallPublic, 2
    jump @bots_game_state_l18
bots_game_state_l19:
    stack 0x4
    stack 0x20
    zero.pri
    retn
pw_isPlayerNode:
    proc
    load.s.pri 0xc
    move.alt
    zero.pri
    xchg
    jsleq @bots_game_state_l21
    load.s.pri 0xc
    const.alt 0x7b070000
    jsless @bots_game_state_l22
    load.s.pri 0xc
    const.alt 0x7b07ffff
    jsgrtr @bots_game_state_l22
    zero.pri
    jump @bots_game_state_l23
bots_game_state_l22:
    const.pri 0x1
bots_game_state_l23:
    jzer @bots_game_state_l21
    const.pri 0x1
    jump @bots_game_state_l24
bots_game_state_l21:
    zero.pri
bots_game_state_l24:
    retn
.public @botHitBy
pw_at_botHitBy:
    proc
    stack -192
    zero.pri
    addr.alt -192
    fill 0xc0
    push.adr 0x10
    push.adr 0xc
    push.c 0x8f18
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 6
    push.s 0x14
    push.adr -192
    sysreq.n sysSetGlobal, 2
    push.adr 0x10
    push.adr 0xc
    push.c 0x8f54
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 6
    push.s 0x18
    push.adr -192
    sysreq.n sysSetGlobal, 2
    push.adr 0x10
    push.adr 0xc
    push.c 0x8fa0
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 6
    push.s 0x1c
    push.adr -192
    sysreq.n sysSetGlobal, 2
    stack -8
    zero.pri
    addr.alt -200
    fill 0x8
    push.adr -200
    sysreq.n netGetSessionTime, 1
    push.adr 0x10
    push.adr 0xc
    push.c 0x8fe4
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 6
    addr.pri -200
    add.c 0x4
    load.i
    push.pri
    push.adr -192
    sysreq.n sysSetGlobal, 2
    stack -4
    push.s 0x24
    push.s 0x20
    push.c 0x8
    call @pw_botAsPlayer
    stor.s.pri -204
    load.s.pri 0x1c
    push.pri
    sysreq.n netGetNodeId, 0
    pop.alt
    jneq @bots_game_state_l26
    push.s 0x1c
    push.c 0x4
    call 0x442c
    move.alt
    load.s.pri 0x24
    jeq @bots_game_state_l26
    zero.pri
    jump @bots_game_state_l27
bots_game_state_l26:
    const.pri 0x1
bots_game_state_l27:
    jzer @bots_game_state_l25
    zero.pri
    stack 0xcc
    retn
bots_game_state_l25:
    push.adr 0x1c
    push.adr -204
    push.c 0x9030
    push.c 0x2b02
    sysreq.n sysCallPublic, 4
    load.s.pri 0x1c
    load.s.alt 0xc
    jeq @bots_game_state_l28
    load.s.pri 0x28
    jzer @bots_game_state_l29
    const.pri 0x9088
    jump @bots_game_state_l30
bots_game_state_l29:
    const.pri 0x90b4
bots_game_state_l30:
    push.pri
    push.c 0x271a
    sysreq.n sysCallPublic, 2
bots_game_state_l28:
    stack 0xcc
    zero.pri
    retn
.public @botAttacks
pw_at_botAttacks:
    proc
    push.s 0x10
    push.c 0x4
    call @pw_isPlayerNode
    jnz @bots_game_state_l32
    load.s.pri 0x10
    const.alt 0x7b070000
    jsless @bots_game_state_l32
    zero.pri
    jump @bots_game_state_l33
bots_game_state_l32:
    const.pri 0x1
bots_game_state_l33:
    jzer @bots_game_state_l31
    zero.pri
    retn
bots_game_state_l31:
    push.c 0x0
    load.s.pri 0x10
    add.c -2064056320
    push.pri
    push.c 0x8
    call @pw_botAsPlayer
    stack -192
    zero.pri
    addr.alt -192
    fill 0xc0
    push.adr 0xc
    push.c 0x90c8
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 5
    push.s 0x10
    push.adr -192
    sysreq.n sysSetGlobal, 2
    load.s.pri 0xc
    push.pri
    sysreq.n netGetNodeId, 0
    pop.alt
    jneq @bots_game_state_l34
    push.adr 0x10
    push.c 0x9108
    push.c 0x2b02
    sysreq.n sysCallPublic, 3
bots_game_state_l34:
    stack 0xc0
    zero.pri
    retn
pw_botShooterOf:
    proc
    push.c 0x916c
    sysreq.n sysGetGlobal, 1
    jnz @bots_game_state_l35
    zero.pri
    retn
bots_game_state_l35:
    stack -192
    zero.pri
    addr.alt -192
    fill 0xc0
    push.adr 0xc
    push.c 0x919c
    push.c 0x0
    push.c 0x30
    push.adr -192
    sysreq.n strformat, 5
    push.adr -192
    sysreq.n sysGetGlobal, 1
    stack 0xc0
    retn
.public @botDown
pw_at_botDown:
    proc
    stack -64
    zero.pri
    addr.alt -64
    fill 0x40
    addr.pri -64
    push.pri
    load.s.pri 0xc
    eq.c.pri 0x1
    jzer @bots_game_state_l36
    const.pri 0x91dc
    jump @bots_game_state_l37
bots_game_state_l36:
    const.pri 0x920c
bots_game_state_l37:
    pop.alt
    movs 0x30
    push.c 0x0
    push.adr -64
    sysreq.n sysGetGlobal, 1
    add.c -1
    push.pri
    sysreq.n max, 2
    push.pri
    push.adr -64
    sysreq.n sysSetGlobal, 2
    stack -4
    push.s 0xc
    push.c 0x4
    call 0x3fec
    stor.s.pri -68
    push.adr -68
    push.adr 0xc
    push.c 0x923c
    push.c 0x271a
    sysreq.n sysCallPublic, 4
    stack -4
    push.s 0xc
    push.s 0x18
    push.c 0x8
    call @pw_botAsPlayer
    stor.s.pri -72
    stack -192
    zero.pri
    addr.alt -264
    fill 0xc0
    push.adr 0x14
    push.adr 0x10
    push.c 0x9274
    push.c 0x0
    push.c 0x30
    push.adr -264
    sysreq.n strformat, 6
    stack -4
    push.adr -264
    sysreq.n sysGetGlobal, 1
    stor.s.pri -268
    stack -384
    zero.pri
    addr.alt -652
    fill 0x180
    stack -384
    zero.pri
    addr.alt -1036
    fill 0x180
    stack -384
    zero.pri
    addr.alt -1420
    fill 0x180
    push.adr -72
    push.c 0x92b8
    push.c 0x0
    push.c 0x30
    push.adr -264
    sysreq.n strformat, 5
    push.c 0x0
    push.c 0x60
    push.adr -1036
    push.adr -264
    sysreq.n sysGetGlobalArray, 4
    push.c 0x60
    push.c 0x92f4
    push.adr -652
    sysreq.n sysGetString, 3
    push.adr -1036
    push.adr -652
    push.c 0x0
    push.c 0x60
    push.adr -1420
    sysreq.n strformat, 5
    push.c 0x0
    push.c 0x0
    push.c 0x100004c
    sysreq.n sndSE, 3
    push.c 0x9318
    sysreq.n sysGetGlobal, 1
    jnz @bots_game_state_l38
    zero.pri
    heap 0x4
    stor.i
    push.alt
    const.pri 0x2
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    const.pri 0x1
    heap 0x4
    stor.i
    push.alt
    push.c 0x9390
    const.pri 0x78
    heap 0x4
    stor.i
    push.alt
    const.pri -1
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    push.adr -1420
    push.c 0x9368
    push.c 0x9348
    push.c 0x2b02
    sysreq.n sysCallPublicf, 12
    heap -28
bots_game_state_l38:
    push.s -268
    push.c 0x4
    call @pw_isPlayerNode
    jzer @bots_game_state_l40
    push.s -268
    push.c 0x4
    call 0x442c
    move.alt
    load.s.pri 0xc
    jeq @bots_game_state_l40
    const.pri 0x1
    jump @bots_game_state_l41
bots_game_state_l40:
    zero.pri
bots_game_state_l41:
    jzer @bots_game_state_l39
    push.s -268
    push.c 0x4
    call 0x45cc
bots_game_state_l39:
    push.adr 0x14
    push.adr 0x10
    push.c 0x93bc
    push.c 0x0
    push.c 0x30
    push.adr -264
    sysreq.n strformat, 6
    stack -4
    push.adr -264
    sysreq.n sysGetGlobal, 1
    stor.s.pri -1424
    push.adr 0x14
    push.adr 0x10
    push.c 0x93f8
    push.c 0x0
    push.c 0x30
    push.adr -264
    sysreq.n strformat, 6
    stack -4
    push.adr -264
    sysreq.n sysGetGlobal, 1
    stor.s.pri -1428
    stack -8
    zero.pri
    addr.alt -1436
    fill 0x8
    push.adr -1436
    sysreq.n netGetSessionTime, 1
    push.adr 0x14
    push.adr 0x10
    push.c 0x9444
    push.c 0x0
    push.c 0x30
    push.adr -264
    sysreq.n strformat, 6
    load.s.pri -1424
    jzer @bots_game_state_l43
    addr.pri -1436
    add.c 0x4
    load.i
    push.pri
    push.adr -264
    sysreq.n sysGetGlobal, 1
    pop.alt
    sub.alt
    const.alt 0x1388
    jsgrtr @bots_game_state_l43
    zero.pri
    jump @bots_game_state_l44
bots_game_state_l43:
    const.pri 0x1
bots_game_state_l44:
    jzer @bots_game_state_l42
    load.s.pri 0x10
    stor.s.pri -1424
    load.s.pri 0x14
    stor.s.pri -1428
bots_game_state_l42:
    push.s -1428
    push.s -1424
    addr.pri -1436
    add.c 0x4
    load.i
    push.pri
    push.s -72
    push.c 0x10
    call 0x6f44
    stack 0x59c
    zero.pri
    retn
