; Generated by tools/pawn2pasm.py from src/bots_torpedo.p: edit the source, then run
;   tools/pawn2pasm.py --version v5200 mods/online/src/bots_torpedo.p
; Target: amx/surface_torpedo.amx of the update v5200 (addresses of v0 translated by tools/amxport.py; the names g_<hex> of the source are those of v0).

.data_at 0x4ecc
.cells $pawn_data 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x0, 0x40, 0x74, 0x6f, 0x72, 0x70, 0x65, 0x64
.cells $pawn_data1 0x6f, 0x48, 0x69, 0x74, 0x0, 0x74, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x0, 0x74
.cells $pawn_data2 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x0, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x67, 0x61
.cells $pawn_data3 0x6d, 0x65, 0x6f, 0x76, 0x65, 0x72, 0x0, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x74, 0x69
.cells $pawn_data4 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x0, 0x6e, 0x70, 0x63, 0x0, 0x6e, 0x70, 0x63, 0x41, 0x63
.cells $pawn_data5 0x74, 0x6f, 0x72, 0x49, 0x64, 0x0, 0x40, 0x74, 0x6f, 0x72, 0x70, 0x65, 0x64, 0x6f, 0x48, 0x69
.cells $pawn_data6 0x74, 0x4f, 0x6e, 0x4e, 0x70, 0x63, 0x54, 0x6f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x0, 0x6e, 0x6f
.cells $pawn_data7 0x64, 0x65, 0x69, 0x64, 0x0, 0x40, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61
.cells $pawn_data8 0x67, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x74, 0x54, 0x6f, 0x72, 0x70, 0x0
.cells $pawn_data9 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74, 0x73, 0x0, 0x40, 0x62, 0x6f, 0x74
.cells $pawn_data10 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x0, 0x62, 0x6f, 0x74, 0x73, 0x68, 0x6f, 0x74, 0x0
.cells $pawn_data11 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x0, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65
.cells $pawn_data12 0x78, 0x0, 0x6e, 0x70, 0x63, 0x0, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x74
.cells $pawn_data13 0x73, 0x0, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x0, 0x74, 0x65, 0x61, 0x6d, 0x43
.cells $pawn_data14 0x6f, 0x6c, 0x6f, 0x72, 0x0, 0x40, 0x62, 0x6f, 0x74, 0x48, 0x69, 0x74, 0x42, 0x79, 0x0, 0x62
.cells $pawn_data15 0x6f, 0x74, 0x73, 0x68, 0x6f, 0x74, 0x0

; ---- hand-written: hooks into the game's code ----
; @eventCollide(other, point): ours first.
.hook 0x6f88
    push.s 0x10
    push.s 0xc
    push.c 8
    call @pw_botTorpedoCollide
    jzer @collide_game
    zero.pri
    retn
collide_game:
    .original
    .return

; ---- compiled ----
pw_botHit:
    proc
    stack -4
    push.s 0xc
    sysreq.n actorGetCollisionType, 1
    stor.s.pri -4
    push.c 0x0
    push.c 0x0
    push.adr -8
    push.c 0x4ecc
    sysreq.n actorGetPropInt, 3
    load.s.pri -8
    load.s.alt 0xc
    jneq @bots_torpedo_l14
    const.pri 0x1
    stack 0x8
    retn
bots_torpedo_l14:
    load.s.pri -4
    const.alt 0x2001
    and
    jzer @bots_torpedo_l15
    zero.pri
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    push.adr 0x18
    load.s.pri 0x10
    add.c 0x8
    push.pri
    load.s.pri 0x10
    add.c 0x4
    push.pri
    push.s 0x10
    push.c 0x4ef0
    push.s 0xc
    sysreq.n sysCallPublic, 8
    heap -8
    const.pri 0x2
    stack 0x8
    retn
bots_torpedo_l15:
    load.s.pri -4
    const.alt 0x80006
    and
    jnz @bots_torpedo_l16
    const.pri 0x1
    stack 0x8
    retn
bots_torpedo_l16:
    push.c 0x0
    push.c 0x0
    push.s 0xc
    push.adr -12
    push.c 0x4f20
    sysreq.n actorGetPropInt, 3
    push.c 0x0
    push.adr -16
    push.c 0x4f48
    sysreq.n actorGetPropInt, 3
    load.s.pri -12
    jzer @bots_torpedo_l18
    load.s.pri -16
    load.s.alt -12
    jneq @bots_torpedo_l18
    const.pri 0x1
    jump @bots_torpedo_l19
bots_torpedo_l18:
    zero.pri
bots_torpedo_l19:
    jzer @bots_torpedo_l17
    const.pri 0x1
    stack 0x10
    retn
bots_torpedo_l17:
    push.c 0x4f70
    sysreq.n sysGetGlobal, 1
    jnz @bots_torpedo_l21
    push.c 0x4fa8
    sysreq.n sysGetGlobal, 1
    jnz @bots_torpedo_l21
    zero.pri
    jump @bots_torpedo_l22
bots_torpedo_l21:
    const.pri 0x1
bots_torpedo_l22:
    jzer @bots_torpedo_l20
    const.pri 0x2
    stack 0x10
    retn
bots_torpedo_l20:
    stack -4
    sysreq.n netGetNodeId, 0
    stor.s.pri -20
    push.c 0x0
    push.s 0xc
    push.adr -24
    push.c 0x4fe8
    sysreq.n actorGetPropInt, 3
    load.s.pri -24
    jzer @bots_torpedo_l23
    stack -4
    push.s 0xc
    sysreq.n actorGetSyncController, 1
    stor.s.pri -28
    push.c 0x0
    push.s 0xc
    push.adr -32
    push.c 0x4ff8
    sysreq.n actorGetPropInt, 3
    const.pri 0x1
    heap 0x4
    stor.i
    push.alt
    push.adr 0x1c
    zero.pri
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    const.pri 0x1
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    push.adr 0x18
    load.s.pri 0x10
    add.c 0x8
    push.pri
    load.s.pri 0x10
    add.c 0x4
    push.pri
    push.s 0x10
    push.adr -32
    push.adr -20
    push.adr -28
    push.c 0x5024
    push.c 0x2710
    sysreq.n netCallPublic, 15
    heap -20
    const.pri 0x2
    stack 0x20
    retn
bots_torpedo_l23:
    push.c 0x0
    push.s 0xc
    push.adr -28
    push.c 0x5084
    sysreq.n actorGetPropInt, 3
    stack -4
    push.c 0x0
    sysreq.n actorGetSyncID, 1
    stor.s.pri -32
    const.pri 0x1
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    zero.pri
    heap 0x4
    stor.i
    push.alt
    load.s.pri 0x10
    add.c 0x8
    push.pri
    load.s.pri 0x10
    add.c 0x4
    push.pri
    push.s 0x10
    push.adr -20
    push.adr 0x14
    push.adr -28
    push.adr -32
    push.c 0x50a0
    push.c 0x2774
    sysreq.n netCallPublic, 12
    heap -12
    push.c 0x510c
    sysreq.n sysGetGlobal, 1
    jzer @bots_torpedo_l24
    push.c 0x0
    call @pw_shooterNode
    heap 0x4
    stor.i
    push.alt
    push.adr -28
    push.c 0x513c
    push.c 0x2b16
    sysreq.n netCallPublic, 4
    heap -4
bots_torpedo_l24:
    load.s.pri -4
    const.alt 0x2
    and
    jzer @bots_torpedo_l25
    const.pri 0x3
    jump @bots_torpedo_l26
bots_torpedo_l25:
    const.pri 0x2
bots_torpedo_l26:
    stack 0x20
    retn
pw_shooterNode:
    proc
    push.c 0x0
    push.c 0x0
    push.adr -4
    push.c 0x516c
    sysreq.n actorGetPropInt, 3
    load.s.pri -4
    jnz @bots_torpedo_l27
    sysreq.n netGetNodeId, 0
    stack 0x4
    retn
bots_torpedo_l27:
    push.c 0x0
    push.c 0x0
    push.c 0x0
    push.adr -8
    push.c 0x518c
    sysreq.n actorGetPropInt, 3
    push.s -8
    push.adr -12
    push.c 0x51b0
    sysreq.n actorGetPropInt, 3
    load.s.pri -12
    jzer @bots_torpedo_l28
    load.s.pri -12
    add.c 0x7b070000
    jump @bots_torpedo_l29
bots_torpedo_l28:
    const.pri -1
bots_torpedo_l29:
    stack 0xc
    retn
pw_noteBotHit:
    proc
    stack -4
    push.s 0xc
    sysreq.n actorGetCollisionType, 1
    stor.s.pri -4
    push.c 0x0
    push.s 0xc
    push.adr -8
    push.c 0x51d4
    sysreq.n actorGetPropInt, 3
    load.s.pri -8
    jzer @bots_torpedo_l31
    load.s.pri -4
    const.alt 0x80004
    and
    jzer @bots_torpedo_l31
    push.c 0x51e4
    sysreq.n sysGetGlobal, 1
    jzer @bots_torpedo_l31
    zero.pri
    jump @bots_torpedo_l32
bots_torpedo_l31:
    const.pri 0x1
bots_torpedo_l32:
    jzer @bots_torpedo_l30
    zero.pri
    stack 0x8
    retn
bots_torpedo_l30:
    push.c 0x0
    push.c 0x0
    push.s 0xc
    push.adr -12
    push.c 0x5214
    sysreq.n actorGetPropInt, 3
    push.s 0xc
    push.adr -16
    push.c 0x5238
    sysreq.n actorGetPropInt, 3
    push.adr 0x10
    push.adr -16
    push.adr -12
    push.c 0x0
    call @pw_shooterNode
    heap 0x4
    stor.i
    push.alt
    push.c 0x0
    sysreq.n actorGetSyncID, 1
    heap 0x4
    stor.i
    push.alt
    sysreq.n netGetNodeId, 0
    heap 0x4
    stor.i
    push.alt
    push.s 0xc
    sysreq.n actorGetSyncID, 1
    heap 0x4
    stor.i
    push.alt
    push.s 0xc
    sysreq.n actorGetSyncController, 1
    heap 0x4
    stor.i
    push.alt
    push.c 0x5260
    push.c 0x2b16
    sysreq.n netCallPublic, 10
    heap -20
    stack 0x10
    zero.pri
    retn
pw_botTorpedoCollide:
    proc
    push.c 0x0
    push.c 0x0
    push.adr -4
    push.c 0x5288
    sysreq.n actorGetPropInt, 3
    load.pri 0x2c1c
    jzer @bots_torpedo_l33
    zero.pri
    stack 0x4
    retn
bots_torpedo_l33:
    load.s.pri -4
    jnz @bots_torpedo_l34
    load.pri 0x2c18
    jnz @bots_torpedo_l35
    push.c 0x0
    push.s 0xc
    push.c 0x8
    call @pw_noteBotHit
bots_torpedo_l35:
    zero.pri
    stack 0x4
    retn
bots_torpedo_l34:
    load.pri 0x2c18
    jzer @bots_torpedo_l36
    const.pri 0x1
    stack 0x4
    retn
bots_torpedo_l36:
    stack -4
    push.c 0x0
    push 0x2574
    push 0x2574
    push.s 0x10
    push.s 0xc
    push.c 0x14
    call @pw_botHit
    stor.s.pri -8
    load.s.pri -8
    eq.c.pri 0x3
    jzer @bots_torpedo_l37
    const.pri 0x1
    stor.pri 0x2c48
bots_torpedo_l37:
    load.s.pri -8
    eq.c.pri 0x2
    jzer @bots_torpedo_l38
    push.c 0x0
    push.s 0xc
    push.c 0x8
    call @pw_noteBotHit
bots_torpedo_l38:
    load.s.pri -8
    const.alt 0x2
    jsless @bots_torpedo_l39
    push.c 0x0
    push.c 0x4
    call 0x8b40
bots_torpedo_l39:
    const.pri 0x1
    stack 0x8
    retn
